// NewLife.Cube.Vuetify/web/src/views/login/index.vue
<template>
  <div class="d-flex justify-center align-center" style="min-height: 100vh; background: linear-gradient(135deg, #1867C0 0%, #5CBBF6 100%);">
    <v-card width="400" class="pa-6">
      <v-card-title class="text-center text-h5 font-weight-bold">登录</v-card-title>
      <v-card-text>
        <v-form @submit.prevent="handleLogin">
          <v-text-field
            v-model="form.username"
            label="用户名"
            prepend-inner-icon="mdi-account"
            variant="outlined"
            density="comfortable"
            class="mb-2"
          />
          <v-text-field
            v-model="form.password"
            label="密码"
            type="password"
            prepend-inner-icon="mdi-lock"
            variant="outlined"
            density="comfortable"
            class="mb-4"
          />
          <v-btn type="submit" color="primary" block size="large" :loading="loading">登录</v-btn>
        </v-form>
      </v-card-text>
      <template v-if="oauthProviders.length">
        <v-divider class="my-4" />
        <v-card-text class="text-center">
          <div class="text-body-2 mb-2">第三方登录</div>
          <div class="d-flex justify-center ga-2">
            <v-btn v-for="p in oauthProviders" :key="p.name" variant="outlined" @click="oauthLogin(p.name)">
              {{ p.displayName || p.name }}
            </v-btn>
          </div>
        </v-card-text>
      </template>
    </v-card>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import type { OAuthProvider } from '@cube/api-core';
import cubeApi from '@/api';
import { useUserStore } from '@/stores/user';

const router = useRouter();
const userStore = useUserStore();

const form = reactive({ username: '', password: '' });
const loading = ref(false);
const oauthProviders = ref<OAuthProvider[]>([]);

onMounted(async () => {
  const res = await cubeApi.config.getLoginConfig();
  if (res.data?.providers) oauthProviders.value = res.data.providers;
});

async function handleLogin() {
  if (!form.username || !form.password) return;
  loading.value = true;
  try {
    const res = await userStore.login(form.username, form.password);
    if (res.data) {
      router.push('/home');
    }
  } finally {
    loading.value = false;
  }
}

function oauthLogin(name: string) {
  window.location.href = `/Sso/LoginExternal?provider=${name}`;
}
</script>

// NewLife.Cube.Angular/web/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzDividerModule } from 'ng-zorro-antd/divider';
import { NzMessageService } from 'ng-zorro-antd/message';
import type { OAuthProvider } from '@cube/api-core';
import { ApiService } from '../../services/api.service';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, NzCardModule, NzFormModule, NzInputModule, NzButtonModule, NzDividerModule],
  template: `
    <div style="display: flex; justify-content: center; align-items: center; min-height: 100vh; background: linear-gradient(135deg, #1890ff 0%, #722ed1 100%);">
      <nz-card style="width: 400px;" [nzBordered]="false">
        <div style="text-align: center; font-size: 20px; font-weight: bold; margin-bottom: 24px;">登录</div>
        <form nz-form (ngSubmit)="handleLogin()">
          <nz-form-item>
            <nz-form-label>用户名</nz-form-label>
            <nz-form-control>
              <input nz-input [(ngModel)]="username" name="username" placeholder="请输入用户名" />
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label>密码</nz-form-label>
            <nz-form-control>
              <input nz-input type="password" [(ngModel)]="password" name="password" placeholder="请输入密码" />
            </nz-form-control>
          </nz-form-item>
          <button nz-button nzType="primary" nzBlock nzSize="large" [nzLoading]="loading">登录</button>
        </form>
        @if (oauthProviders.length) {
          <nz-divider nzText="第三方登录"></nz-divider>
          <div style="display: flex; gap: 8px; justify-content: center;">
            @for (p of oauthProviders; track p.name) {
              <button nz-button (click)="oauthLogin(p.name)">{{ p.displayName || p.name }}</button>
            }
          </div>
        }
      </nz-card>
    </div>
  `,
})
export class LoginComponent implements OnInit {
  username = '';
  password = '';
  loading = false;
  oauthProviders: OAuthProvider[] = [];

  constructor(
    private api: ApiService,
    private userService: UserService,
    private router: Router,
    private message: NzMessageService,
  ) {}

  async ngOnInit() {
    const res = await this.api.config.getLoginConfig();
    if (res.data?.providers) this.oauthProviders = res.data.providers;
  }

  async handleLogin() {
    if (!this.username || !this.password) {
      this.message.warning('请输入用户名和密码');
      return;
    }
    this.loading = true;
    try {
      const res = await this.userService.login(this.username, this.password);
      if (res.data) {
        this.message.success('登录成功');
        this.router.navigate(['/home']);
      } else {
        this.message.error(res.message || '登录失败');
      }
    } finally {
      this.loading = false;
    }
  }

  oauthLogin(name: string) {
    window.location.href = `/Sso/LoginExternal?provider=${name}`;
  }
}
