// NewLife.Cube.Angular/web/src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzStatisticModule } from 'ng-zorro-antd/statistic';
import { NzGridModule } from 'ng-zorro-antd/grid';
import { NzPageHeaderModule } from 'ng-zorro-antd/page-header';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, NzCardModule, NzStatisticModule, NzGridModule, NzPageHeaderModule],
  template: `
    <nz-page-header nzTitle="首页" nzSubtitle="系统概览" [nzBack]="null"></nz-page-header>
    <div nz-row [nzGutter]="16">
      @for (card of stats; track card.title) {
        <div nz-col [nzXs]="24" [nzSm]="12" [nzMd]="6">
          <nz-card>
            <nz-statistic [nzTitle]="card.title" [nzValue]="card.value"></nz-statistic>
          </nz-card>
        </div>
      }
    </div>
  `,
})
export class HomeComponent {
  stats = [
    { title: '用户总数', value: 0 },
    { title: '今日访问', value: 0 },
    { title: '在线用户', value: 0 },
    { title: '系统消息', value: 0 },
  ];
}

// NewLife.Cube.ArcoVue/web/src/views/home/index.vue
<template>
  <div>
    <a-page-header title="首页" subtitle="系统概览" :show-back="false" />
    <a-grid :cols="{ xs: 1, sm: 2, md: 4 }" :col-gap="16" :row-gap="16" style="padding: 0 16px;">
      <a-grid-item v-for="card in stats" :key="card.title">
        <a-card hoverable>
          <a-statistic :title="card.title" :value="card.value" />
        </a-card>
      </a-grid-item>
    </a-grid>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

defineOptions({ name: 'Home' });

const stats = ref([
  { title: '用户总数', value: 0 },
  { title: '今日访问', value: 0 },
  { title: '在线用户', value: 0 },
  { title: '系统消息', value: 0 },
]);
</script>
