// NewLife.Cube.Vue/web/core/components/ai/AiAssistant.vue
<!--
 * 魔方 AI 助手（Vue 版）悬浮窗
 * 右下角对话面板：SSE 流式对话 + 工具调用可视化 + 表单智能填充
 * 协议与 MVC 版 ai-assistant.js 一致：POST /Ai/AiChat（body 携带 area/controller 目标页面）→ SSE {type:content_delta|tool_call_start|tool_call_done|tool_call_error|run_js|error}
 -->
<template>
  <div v-if="enabled" class="ai-assistant" :class="{ 'panel-open': visible }" :style="aiStyle">
    <!-- 悬浮球 -->
    <div class="ai-fab" :title="'AI 助手'" @click="visible = !visible">
      <svg viewBox="0 0 24 24" width="26" height="26" aria-hidden="true">
        <g fill="#2ecc71">
          <circle cx="12" cy="7" r="4.6" />
          <circle cx="17" cy="12" r="4.6" />
          <circle cx="12" cy="17" r="4.6" />
          <circle cx="7" cy="12" r="4.6" />
        </g>
        <circle cx="12" cy="12" r="2.6" fill="#ffffff" />
      </svg>
    </div>

    <!-- 对话面板 -->
    <Transition name="ai-fade">
      <div v-if="visible" class="ai-panel" :class="{ maximized }">
        <div class="ai-panel-header">
          <span class="ai-title">
            <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
              <g fill="#2ecc71">
                <circle cx="12" cy="7" r="4.6" />
                <circle cx="17" cy="12" r="4.6" />
                <circle cx="12" cy="17" r="4.6" />
                <circle cx="7" cy="12" r="4.6" />
              </g>
              <circle cx="12" cy="12" r="2.6" fill="#ffffff" />
            </svg>
            AI 助手
          </span>
          <div class="ai-actions">
            <el-button text size="small" :title="maximized ? '还原' : '最大化'" @click="toggleMaximize"><el-icon><FullScreen v-if="!maximized" /><CopyDocument v-else /></el-icon></el-button>
            <el-button text size="small" title="清空会话" @click="clear"><el-icon><Delete /></el-icon></el-button>
            <el-button text size="small" title="收起" @click="visible = false"><el-icon><Close /></el-icon></el-button>
          </div>
        </div>

        <div class="ai-messages" ref="msgBox">
          <!-- 欢迎语 + 快捷指令 -->
          <div v-if="messages.length === 0" class="ai-welcome">
            <p>你好，我是魔方 AI 助手 👋 我可以帮你分析当前数据、填写表单、检查系统状态。</p>
            <div class="ai-quick">
              <el-button v-if="page === 'list'" size="small" round @click="quick('分析当前列表数据')">📊 分析当前数据</el-button>
              <el-button v-if="page === 'form'" size="small" round @click="quick('帮我填写当前表单')">📝 帮我填表</el-button>
              <el-button size="small" round @click="quick('检查系统运行状态')">🩺 系统诊断</el-button>
            </div>
          </div>

          <!-- 消息 -->
          <template v-for="m in messages" :key="m.id">
            <div v-if="m.type === 'user'" class="ai-msg ai-user"><div class="ai-bubble">{{ m.text }}</div></div>
            <div v-else-if="m.type === 'assistant'" class="ai-msg ai-assistant"><div class="ai-bubble" v-html="m.html"></div></div>
          </template>

          <!-- 工具卡片 -->
          <div v-for="t in toolCards" :key="t.id" class="ai-tool" :class="{ 'ai-tool-done': t.status === 'done', 'ai-tool-error': t.status === 'error' }">
            <template v-if="t.status === 'start'"><span>🔧 正在调用 <b>{{ t.name }}</b>...</span></template>
            <template v-else-if="t.status === 'done'"><span>✅ <b>{{ t.name }}</b> 完成</span></template>
            <template v-else><span>❌ <b>{{ t.name }}</b> 失败</span></template>
          </div>
        </div>

        <div class="ai-panel-footer">
          <label class="ai-think" title="深度推理更准确，但耗时更长">
            <el-checkbox v-model="think">深度</el-checkbox>
          </label>
          <el-input
            v-model="input"
            type="textarea"
            :rows="1"
            resize="none"
            placeholder="输入问题，Enter 发送，Shift+Enter 换行"
            @keydown.enter.exact.prevent="send"
          />
          <el-button type="primary" circle :icon="Promotion" title="发送" :loading="streaming" @click="send" />
        </div>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { ElMessage } from 'element-plus';
import { Delete, Close, Promotion, FullScreen, CopyDocument } from '@element-plus/icons-vue';
import { marked } from 'marked';
import { getAccessToken } from '../../utils/token';
import { renderMermaidBlocks } from './mermaidRenderer';

interface Props {
  /** 页面类型：list / form / detail */
  page: string;
  /** 表单模式：add / edit */
  mode?: string;
  /** 记录编号 */
  id?: number;
  /** 列表页查询条件（_query Base64），表单页可空 */
  query?: string;
  /** 目标页面控制器路径，如 'Admin/User' 或 'User'。请求统一走全局端点 /Ai/AiChat，经 area/controller 解析目标控制器能力 */
  url: string;
}
const props = withDefaults(defineProps<Props>(), {
  mode: 'add',
  id: 0,
  query: '',
});

const emit = defineEmits<{
  /** fill_form 工具完成，携带生成的字段值，由宿主合并到表单 */
  (e: 'fill-form', values: Record<string, any>): void;
}>();

interface Msg {
  id: number;
  type: 'user' | 'assistant';
  text?: string;
  html: string;
}
interface ToolCard {
  id: string;
  name: string;
  status: 'start' | 'done' | 'error';
}

const visible = ref(false);
const think = ref(false);
/** 全屏放大状态，localStorage 持久化，重开面板自动恢复 */
const maximized = ref(localStorage.getItem('cube-ai-maximized') === '1');

/** AI 助手开关与配色（来自 /Cube/GetAiConfig，CubeSetting 配置） */
const enabled = ref(false);
const primaryColor = ref('#2ecc71');
const secondaryColor = ref('#1e8e3e');
/** Mermaid 图表库 CDN 地址（来自 GetAiConfig，首次遇到图表才懒加载） */
const mermaidUrl = ref('');

/** 根元素 CSS 变量，驱动全部浮窗配色 */
const aiStyle = computed(() => ({
  '--ai-primary': primaryColor.value,
  '--ai-secondary': secondaryColor.value,
}));
const input = ref('');
const streaming = ref(false);
const messages = ref<Msg[]>([]);
const toolCards = ref<ToolCard[]>([]);
const msgBox = ref<HTMLElement>();

let seq = 0;

/** 页面标识：会话按页面隔离。不同页面互不串话，同页多轮共享，刷新/返回恢复 */
const pageKey = ref(location.pathname || '/');
const sessionKey = () => 'cube-ai-session:' + pageKey.value;

/** 读取或创建当前页面的会话号（sessionStorage 按标签页×页面隔离） */
function loadSessionId(): string {
  let sid = sessionStorage.getItem(sessionKey());
  if (!sid) {
    sid = 's' + Date.now() + Math.random().toString(16).substring(2, 8);
    sessionStorage.setItem(sessionKey(), sid);
  }
  return sid;
}
let sessionId = loadSessionId();

// SPA 路由切换（组件常驻不重挂载）时切换会话：按新页面路径读取/创建会话号
let route: { path: string } | undefined;
try {
  route = useRoute();
} catch {
  /* 非路由上下文（独立挂载）时忽略 */
}
if (route) {
  watch(
    () => route!.path,
    (path) => {
      if (path && path !== pageKey.value) {
        pageKey.value = path;
        sessionId = loadSessionId();
      }
    },
  );
}

/** HTML 转义，防止 AI 输出的 raw HTML 注入（XSS） */
function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Markdown 渲染：marked 库（GFM + 单换行断行 + XSS 防护） */
function renderMarkdown(text: string): string {
  if (!text) return '';
  return marked.parse(text, {
    gfm: true,
    breaks: true, // 单换行 → <br>，AI 流式输出友好
    renderer: {
      // 安全：AI 输出中的 raw HTML 一律转义显示，防止 XSS
      html: ({ text: t }: { text: string }) => escapeHtml(t),
      // 代码块：语言徽标 + 内容转义 + 深色样式
      code: ({ text: t, lang }: { text: string; lang?: string }) => {
        const l = (lang || '').match(/^\S+/)?.[0] || '';
        const label = l ? `<span class="ai-code-lang">${escapeHtml(l)}</span>` : '';
        const body = String(t).replace(/\n+$/, '');
        return `<pre>${label}<code class="language-${escapeHtml(l)}">${escapeHtml(body)}</code></pre>`;
      },
    } as any,
  }) as string;
}

function scrollBottom() {
  nextTick(() => {
    if (msgBox.value) msgBox.value.scrollTop = msgBox.value.scrollHeight;
  });
}

/** 切换全屏放大：占满视口留 20px 边距，状态持久化，重开面板自动恢复 */
function toggleMaximize() {
  maximized.value = !maximized.value;
  localStorage.setItem('cube-ai-maximized', maximized.value ? '1' : '0');
  scrollBottom();
}

function appendUser(text: string) {
  messages.value.push({ id: ++seq, type: 'user', text, html: '' });
  scrollBottom();
}
function appendAssistant(): Msg {
  const m: Msg = { id: ++seq, type: 'assistant', html: '' };
  messages.value.push(m);
  scrollBottom();
  return m;
}

/** 处理工具事件（规范协议：tool_call_start / tool_call_done / tool_call_error，工具编号字段 toolCallId） */
function handleTool(status: 'start' | 'done' | 'error', json: any) {
  const id = json.toolCallId || '';
  const name = json.name || '';
  let card = toolCards.value.find((t) => t.id === id);
  if (!card) {
    card = { id, name, status: 'start' };
    toolCards.value.push(card);
  }
  if (status === 'start') {
    card.name = name || card.name;
    card.status = 'start';
  } else if (status === 'done') {
    card.status = 'done';
    // fill_form 完成 → 表单值交给宿主合并（结果字段 result）
    if (name === 'fill_form' && json.result) {
      try {
        const data = JSON.parse(json.result);
        if (data && data.kind === 'fill_form' && data.values) {
          emit('fill-form', data.values as Record<string, any>);
          const names = Object.keys(data.values).join('、');
          ElMessage.success(`AI 已预填 ${Object.keys(data.values).length} 个字段（${names}），请检查后保存`);
        }
      } catch {
        /* 解析失败忽略 */
      }
    }
  } else {
    card.status = 'error';
  }
  scrollBottom();
}

/** 序列化脚本执行结果，处理循环引用/函数等无法 JSON 化的值 */
function serializeResult(v: any): string {
  if (v === undefined) return 'undefined';
  if (v === null) return 'null';
  if (typeof v === 'function') return '[Function]';
  if (typeof v === 'symbol' || typeof v === 'bigint') return String(v);
  if (typeof v === 'object') {
    try {
      const s = JSON.stringify(v);
      return s === undefined ? String(v) : s;
    } catch {
      return String(v);
    }
  }
  return JSON.stringify(v);
}

/** 获取浏览器操作回传端点：全局 AI 控制器 OperationResult（统一无区域前缀），所有实体页面共用 */
function getAiOperationUrl(): string {
  return '/Ai/OperationResult';
}

/** 回传浏览器操作结果到全局 AI 控制器，完成等待中的工具调用 */
async function postOperationResult(checkpointId: string, result: string) {
  try {
    await fetch(getAiOperationUrl(), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(getAccessToken() ? { Authorization: `${getAccessToken()}` } : {}),
      },
      body: JSON.stringify({ checkpointId, result }),
    });
  } catch {
    // 回传失败忽略，后端会超时自动失败
  }
}

/** 处理后端下发的 run_js 事件：执行脚本并回传结果 */
function handleRunJs(json: any) {
  const checkpointId = json.checkpointId as string;
  const script = (json.script as string) || '';
  let result: string;
  try {
    const fn = new Function(script);
    const v = fn();
    result = JSON.stringify({ ok: true, value: serializeResult(v) });
  } catch (e: any) {
    result = JSON.stringify({ ok: false, error: e?.message || String(e) });
  }
  // 结果过大时截断，避免请求体膨胀
  if (result.length > 8192) result = result.substring(0, 8192);
  postOperationResult(checkpointId, result);
}

/** 发送消息 */
async function send() {
  if (streaming.value) return;
  const text = input.value.trim();
  if (!text) return;
  input.value = '';
  streaming.value = true;

  appendUser(text);
  const am = appendAssistant();
  let full = '';

  // 解析目标页面标识：url 如 'Admin/User' → area='Admin', controller='User'；'User' → area=''
  const urlParts = (props.url || '').split('/');
  const targetController = urlParts[urlParts.length - 1] || '';
  const targetArea = urlParts.length > 1 ? urlParts.slice(0, -1).join('/') : '';

  try {
    // 统一走全局 AI 端点，服务端按 area/controller 解析目标控制器能力（实体数据工具/页面上下文/通用工具）
    const resp = await fetch('/Ai/AiChat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(getAccessToken() ? { Authorization: `${getAccessToken()}` } : {}),
      },
      body: JSON.stringify({
        sessionId,
        message: text,
        page: props.page,
        mode: props.mode,
        id: props.id || 0,
        query: props.query || '',
        area: targetArea,
        controller: targetController,
        url: location.pathname,
        think: think.value,
      }),
    });
    if (!resp.ok) {
      let msg = 'HTTP ' + resp.status;
      try {
        const data = await resp.json();
        if (data?.message) msg = data.message;
      } catch {
        /* ignore */
      }
      throw new Error(msg);
    }

    const reader = resp.body!.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop() || '';
      for (const line of lines) {
        const t = line.trim();
        if (!t.startsWith('data: ')) continue;
        let json: any;
        try {
          json = JSON.parse(t.substring(6));
        } catch {
          continue;
        }
        if (!json) continue;
        if (json.type === 'content_delta') {
          full += json.content || '';
          am.html = renderMarkdown(full);
          scrollBottom();
        } else if (json.type === 'tool_call_start') {
          handleTool('start', json);
        } else if (json.type === 'tool_call_done') {
          handleTool('done', json);
        } else if (json.type === 'tool_call_error') {
          handleTool('error', json);
        } else if (json.type === 'run_js') {
          handleRunJs(json);
        } else if (json.type === 'error') {
          am.html = `<span style="color:#c62828">⚠️ ${json.message || 'AI 调用失败'}</span>`;
          scrollBottom();
        }
        // message_start / message_done / thinking_delta / heartbeat 规范事件无需处理，忽略
      }
    }
  } catch (err: any) {
    am.html = `<span style="color:#c62828">⚠️ ${err?.message || '请求失败'}</span><br><small>请确认 AI 服务已启用（系统设置中开启 AISwitch）</small>`;
  } finally {
    // 标记遗留"正在调用"的工具卡片为中断
    for (const c of toolCards.value) {
      if (c.status === 'start') {
        c.status = 'error';
        c.name = c.name + '（中断）';
      }
    }
    streaming.value = false;
    // AI 回复结束后渲染 Mermaid 图表（流式期间保持源码展示，避免逐字重渲染）
    nextTick(() => renderMermaidBlocks(msgBox.value, mermaidUrl.value));
  }
}

/** 快捷指令 */
function quick(prompt: string) {
  input.value = prompt;
  send();
}

/** 清空会话（仅当前页面，不影响其他页面） */
function clear() {
  messages.value = [];
  toolCards.value = [];
  sessionStorage.removeItem(sessionKey());
  sessionId = loadSessionId();
}

/** 加载 AI 助手配置：开关控制渲染，配色注入 CSS 变量 */
async function loadConfig() {
  try {
    const resp = await fetch('/Cube/GetAiConfig', {
      headers: getAccessToken() ? { Authorization: `${getAccessToken()}` } : {},
    });
    if (!resp.ok) return;
    const json = await resp.json();
    const data = json?.data;
    if (data) {
      enabled.value = !!data.AISwitch;
      if (data.AIPrimaryColor) primaryColor.value = data.AIPrimaryColor;
      if (data.AISecondaryColor) secondaryColor.value = data.AISecondaryColor;
      if (data.MermaidUrl) mermaidUrl.value = data.MermaidUrl;
    }
  } catch {
    // 配置获取失败时保持默认配色，且不显示浮窗（AISwitch 默认关闭）
  }
}
onMounted(loadConfig);
</script>

<style scoped>
.ai-assistant {
  position: fixed;
  right: 24px;
  bottom: 24px;
  z-index: 3000;
}
.ai-assistant.panel-open .ai-fab {
  /* 面板打开时隐藏悬浮球，关闭后恢复显示 */
  display: none;
}
.ai-fab {
  width: 52px;
  height: 52px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--ai-primary) 0%, var(--ai-secondary) 100%);
  box-shadow: 0 4px 14px color-mix(in srgb, var(--ai-primary) 50%, transparent);
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: transform 0.2s;
}
.ai-fab:hover {
  transform: scale(1.08);
}
.ai-panel {
  position: absolute;
  right: 0;
  bottom: 64px;
  width: 460px;
  height: 70vh;
  min-height: 400px;
  background: var(--el-bg-color);
  border-radius: 12px;
  box-shadow: 0 8px 30px color-mix(in srgb, var(--el-color-black) 18%, transparent);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.ai-assistant.panel-open .ai-panel {
  /* 面板打开时下沉到悬浮球位置，多占约 64px 高度 */
  bottom: 0;
}
.ai-panel.maximized {
  /* 全屏放大态：占满视口留 20px 边距 */
  position: fixed;
  left: 20px;
  top: 20px;
  right: 20px;
  bottom: 20px;
  width: auto;
  height: auto;
  border-radius: 12px;
}
.ai-panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 14px;
  background: linear-gradient(135deg, var(--ai-primary) 0%, var(--ai-secondary) 100%);
  color: var(--el-color-white);
  font-weight: 600;
}
.ai-panel-header .el-button {
  color: var(--el-color-white);
}
.ai-messages {
  flex: 1;
  overflow-y: auto;
  padding: 14px;
}
.ai-welcome {
  color: var(--el-text-color-regular);
  font-size: 13px;
}
.ai-welcome p {
  margin: 0 0 10px;
}
.ai-quick {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}
.ai-msg {
  margin-bottom: 10px;
  display: flex;
}
/* 用户/AI 消息气泡满宽，仅靠颜色区分，避免左右留白浪费 */
.ai-msg .ai-bubble {
  width: 100%;
  padding: 8px 12px;
  border-radius: 10px;
  font-size: 13px;
  line-height: 1.6;
  word-break: break-word;
}
.ai-user .ai-bubble {
  background: var(--ai-primary);
  color: var(--el-color-white);
  border-top-right-radius: 2px;
}
.ai-assistant .ai-bubble {
  background: var(--el-fill-color);
  color: var(--el-text-color-primary);
  border-top-left-radius: 2px;
}
.ai-assistant .ai-bubble :deep(h1), .ai-assistant .ai-bubble :deep(h2), .ai-assistant .ai-bubble :deep(h3), .ai-assistant .ai-bubble :deep(h4) {
  margin: 8px 0 4px;
}
.ai-assistant .ai-bubble :deep(p) {
  margin: 4px 0;
}
.ai-assistant .ai-bubble :deep(code) {
  background: var(--el-fill-color-darker);
  padding: 1px 4px;
  border-radius: 3px;
  font-family: Consolas, Monaco, 'Courier New', monospace;
  font-size: 90%;
}
.ai-assistant .ai-bubble :deep(pre) {
  background: color-mix(in srgb, var(--el-color-black) 88%, transparent);
  color: color-mix(in srgb, var(--el-color-white) 83%, transparent);
  padding: 10px 12px;
  border-radius: 6px;
  overflow-x: auto;
  margin: 6px 0;
  position: relative;
}
.ai-assistant .ai-bubble :deep(pre code) {
  background: none;
  padding: 0;
  color: inherit;
  font-size: 90%;
}
.ai-assistant .ai-bubble :deep(.ai-mermaid) {
  overflow-x: auto;
  margin: 6px 0;
}
.ai-assistant .ai-bubble :deep(.ai-mermaid svg) {
  max-width: 100%;
  height: auto;
  display: block;
}
.ai-assistant .ai-bubble :deep(.ai-mermaid details) {
  margin-top: 6px;
}
.ai-assistant .ai-bubble :deep(.ai-mermaid summary) {
  cursor: pointer;
  color: var(--el-text-color-secondary);
  font-size: 12px;
  user-select: none;
}
.ai-assistant .ai-bubble :deep(.ai-code-lang) {
  position: absolute;
  top: 4px;
  right: 8px;
  font-size: 10px;
  color: var(--el-text-color-secondary);
  text-transform: uppercase;
  user-select: none;
}
.ai-assistant .ai-bubble :deep(table) {
  border-collapse: collapse;
  width: 100%;
  margin: 6px 0;
}
.ai-assistant .ai-bubble :deep(th),
.ai-assistant .ai-bubble :deep(td) {
  border: 1px solid var(--el-border-color);
  padding: 4px 6px;
  font-size: 12px;
}
.ai-assistant .ai-bubble :deep(th) {
  background: var(--el-fill-color-light);
}
.ai-assistant .ai-bubble :deep(a) {
  color: var(--ai-primary);
  text-decoration: underline;
}
.ai-assistant .ai-bubble :deep(hr) {
  border: none;
  border-top: 1px solid var(--el-border-color-lighter);
  margin: 8px 0;
}
.ai-assistant .ai-bubble :deep(ul),
.ai-assistant .ai-bubble :deep(ol) {
  padding-left: 18px;
  margin: 4px 0;
}
.ai-assistant .ai-bubble :deep(li) {
  margin: 2px 0;
}
.ai-assistant .ai-bubble :deep(input[type='checkbox']) {
  margin-right: 4px;
}
.ai-assistant .ai-bubble :deep(blockquote) {
  border-left: 3px solid var(--ai-primary);
  margin: 6px 0;
  padding: 4px 10px;
  background: color-mix(in srgb, var(--ai-primary) 6%, var(--el-color-white));
  color: var(--el-text-color-regular);
}
.ai-tool {
  font-size: 12px;
  color: var(--el-text-color-regular);
  background: var(--el-fill-color-lighter);
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 6px;
  padding: 6px 10px;
  margin-bottom: 6px;
}
.ai-tool-done {
  color: var(--el-color-success-dark-2);
  border-color: var(--el-color-success-light-7);
  background: var(--el-color-success-light-9);
}
.ai-tool-error {
  color: var(--el-color-danger-dark-2);
  border-color: var(--el-color-danger-light-7);
  background: var(--el-color-danger-light-9);
}
.ai-panel-footer {
  display: flex;
  align-items: flex-end;
  gap: 8px;
  padding: 10px 12px;
  border-top: 1px solid var(--el-border-color-lighter);
}
.ai-think {
  flex-shrink: 0;
  padding-bottom: 6px;
  font-size: 12px;
  color: var(--el-text-color-regular);
}
.ai-panel-footer .el-textarea {
  flex: 1;
}
.ai-fade-enter-active,
.ai-fade-leave-active {
  transition: opacity 0.2s, transform 0.2s;
}
.ai-fade-enter-from,
.ai-fade-leave-to {
  opacity: 0;
  transform: translateY(10px);
}
</style>

// NewLife.Cube.React/web/src/components/ai/AiAssistant.tsx
/**
 * AI 助手（右下角对话面板，对齐 Vue 皮肤 components/ai/AiAssistant.vue + MVC ai-assistant.js）
 *
 * 协议：POST /Ai/AiChat（body 携带 area/controller 目标页面 + sessionId 会话号）→ SSE
 *   {type: content_delta|tool_call_start|tool_call_done|tool_call_error|run_js|error}
 * 能力：
 * - AISwitch 开关门控：GetAiConfig 读取，关闭时不渲染（对齐 Vue v-if="enabled"）
 * - 会话管理：sessionStorage 按页面隔离，SPA 路由切换自动切换，多轮共享历史
 * - 快捷指令：按页面类型一键任务（分析当前数据 / 帮我填表 / 系统诊断）
 * - run_js 浏览器操作：执行后端下发脚本，POST /Ai/OperationResult 回传（AI-10）
 * - fill_form 表单填充：派发 cube:ai-fill-form 事件，表单页监听 setFieldsValue
 * - think 深度推理开关 + 最大化/清空会话
 * - 流式渲染 Markdown；结束后渲染 Mermaid 图表（CDN 懒加载）
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import { Button, Checkbox, Input, Space, Tooltip } from 'antd';
import {
  CloseOutlined,
  DeleteOutlined,
  FullscreenExitOutlined,
  FullscreenOutlined,
  RobotOutlined,
  SendOutlined,
} from '@ant-design/icons';
import { useLocation } from 'react-router-dom';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import { api } from '@/api';
import { renderMermaidBlocks } from './mermaidRenderer';

interface ChatMsg {
  id: number;
  type: 'user' | 'assistant';
  html: string;
}

interface ToolCard {
  id: string;
  name: string;
  status: 'start' | 'done' | 'error';
}

/** AI 助手配置（/Cube/GetAiConfig 返回，FastJson camelCase） */
interface AiConfigPayload {
  /** AI 总开关（兼容 PascalCase 旧键） */
  aISwitch?: boolean;
  AISwitch?: boolean;
  /** 主色 */
  aIPrimaryColor?: string;
  /** 辅色 */
  aISecondaryColor?: string;
  /** Mermaid 图表库 CDN 地址 */
  mermaidUrl?: string;
}

let seq = 0;

/** HTML 转义，防止用户输入被当作标记注入（用户消息回显时使用） */
function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

/** 页面会话键：/Admin/User → 'Admin/User' */
function pageKeyOf(pathname: string): string {
  return pathname.replace(/^\//, '') || '/';
}

/** 读取或创建当前页面的会话号（sessionStorage 按标签页×页面隔离，多轮对话共享历史） */
function loadSessionId(key: string): string {
  let sid = sessionStorage.getItem('cube-ai-session:' + key);
  if (!sid) {
    sid = 's' + Date.now() + Math.random().toString(16).substring(2, 8);
    sessionStorage.setItem('cube-ai-session:' + key, sid);
  }
  return sid;
}

/** 序列化 run_js 脚本执行结果，处理循环引用/函数等无法 JSON 化的值 */
function serializeResult(v: unknown): string {
  if (v === undefined) return 'undefined';
  if (v === null) return 'null';
  if (typeof v === 'function') return '[Function]';
  if (typeof v === 'symbol' || typeof v === 'bigint') return String(v);
  if (typeof v === 'object') {
    try {
      const s = JSON.stringify(v);
      return s === undefined ? String(v) : s;
    } catch {
      return String(v);
    }
  }
  return JSON.stringify(v);
}

/** 是否表单类路径（含 ?id= 或 /Edit /Add /New /Detail 后缀，与 DefaultEntityPage 一致） */
function isFormPath(pathname: string, search: string): boolean {
  if (search.includes('id=')) return true;
  return /\/+(edit|add|new|detail)$/i.test(pathname);
}

/** 页面是否含表单（antd Form 渲染 <form class="ant-form">，字段控件无 name 属性，按容器判定）。
 * 覆盖配置页（ConfigPage/魔方设置）、表单页（FormPage）与列表弹窗表单（FormDialog） */
function hasFormControls(): boolean {
  return !!document.querySelector('form.ant-form, .ant-form');
}

/** 从 /Cube/GetAiConfig 加载 AI 配置：开关门控 + 配色 + Mermaid CDN 地址 */
async function loadAiConfig(): Promise<AiConfigPayload> {
  try {
    const res = await api.client.get('/Cube/GetAiConfig');
    return ((res.data as { data?: AiConfigPayload })?.data ?? {}) as AiConfigPayload;
  } catch {
    return {};
  }
}

export default function AiAssistant() {
  const location = useLocation();
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<ChatMsg[]>([]);
  const [tools, setTools] = useState<ToolCard[]>([]);
  const [streaming, setStreaming] = useState(false);
  const [think, setThink] = useState(false);
  /** AI 总开关：AISwitch 关闭时不渲染悬浮球（对齐 Vue） */
  const [enabled, setEnabled] = useState(false);
  /** 最大化状态，localStorage 持久化，重开面板自动恢复 */
  const [maximized, setMaximized] = useState(() => localStorage.getItem('cube-ai-maximized') === '1');
  const bodyRef = useRef<HTMLDivElement>(null);
  const mermaidUrlRef = useRef('');
  const sessionIdRef = useRef('');

  /** 页面会话键（路由切换时更新，驱动会话切换） */
  const [pageKey, setPageKey] = useState(() => pageKeyOf(location.pathname));

  // 页面类型上下文：list / form，及编辑态与记录编号
  const [pageKind, setPageKind] = useState<'list' | 'form'>('list');
  const [isEdit, setIsEdit] = useState(false);
  const [recordId, setRecordId] = useState(0);

  // 路由切换 → 切换会话键（组件常驻不重挂载）
  useEffect(() => {
    setPageKey(pageKeyOf(location.pathname));
  }, [location.pathname]);

  // 会话号随页面键切换
  useEffect(() => {
    sessionIdRef.current = loadSessionId(pageKey);
  }, [pageKey]);

  // 加载 AI 配置（开关门控 + Mermaid CDN）
  useEffect(() => {
    let cancelled = false;
    void loadAiConfig().then((cfg) => {
      if (cancelled) return;
      setEnabled(!!(cfg.aISwitch ?? cfg.AISwitch));
      mermaidUrlRef.current = cfg.mermaidUrl ?? '';
    });
    return () => {
      cancelled = true;
    };
  }, []);

  // 页面上下文：URL + DOM 表单控件探测 → page/mode/id
  useEffect(() => {
    const form = isFormPath(location.pathname, location.search) || hasFormControls();
    setPageKind(form ? 'form' : 'list');
    const id = Number(new URLSearchParams(location.search).get('id') ?? 0) || 0;
    // 兼容 /Detail/{id} 路径
    const m = location.pathname.match(/\/Detail\/(\d+)/i);
    const rid = id || (m ? Number(m[1]) : 0);
    setRecordId(rid);
    setIsEdit(rid > 0 || /\/+(edit|detail)$/i.test(location.pathname));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [location.pathname, location.search, open]);

  // 目标页面标识：/Admin/User → area=Admin, controller=User
  const urlParts = location.pathname.replace(/^\//, '').split('/');
  const targetController = urlParts[urlParts.length - 1] || '';
  const targetArea = urlParts.length > 1 ? urlParts.slice(0, -1).join('/') : '';

  const scrollBottom = () => {
    requestAnimationFrame(() => {
      if (bodyRef.current) bodyRef.current.scrollTop = bodyRef.current.scrollHeight;
    });
  };

  const renderMarkdown = (text: string): string => {
    const html = marked.parse(text, { breaks: true, gfm: true }) as string;
    return DOMPurify.sanitize(html);
  };

  /** 切换最大化，状态持久化，重开面板自动恢复 */
  const toggleMaximize = () => {
    setMaximized((m) => {
      const next = !m;
      localStorage.setItem('cube-ai-maximized', next ? '1' : '0');
      return next;
    });
    scrollBottom();
  };

  /** 清空当前页面会话（不影响其他页面） */
  const handleClear = () => {
    setMessages([]);
    setTools([]);
    const key = pageKeyOf(location.pathname);
    sessionStorage.removeItem('cube-ai-session:' + key);
    sessionIdRef.current = loadSessionId(key);
  };

  /** 回传浏览器操作结果到全局 AI 控制器，完成等待中的工具调用 */
  const postOperationResult = async (checkpointId: string, result: string) => {
    try {
      const token = api.tokenManager.getToken();
      await fetch('/Ai/OperationResult', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ checkpointId, result }),
      });
    } catch {
      // 回传失败忽略，后端会超时自动失败
    }
  };

  /** 处理后端下发的 run_js 事件：执行脚本并回传结果 */
  const handleRunJs = (json: Record<string, unknown>) => {
    const checkpointId = String(json.checkpointId ?? '');
    const script = String(json.script ?? '');
    let result: string;
    try {
      const fn = new Function(script);
      const v = fn();
      result = JSON.stringify({ ok: true, value: serializeResult(v) });
    } catch (e) {
      result = JSON.stringify({ ok: false, error: (e as Error)?.message || String(e) });
    }
    // 结果过大时截断，避免请求体膨胀
    if (result.length > 8192) result = result.substring(0, 8192);
    void postOperationResult(checkpointId, result);
  };

  /** 处理工具事件（规范协议：tool_call_start / tool_call_done / tool_call_error） */
  const handleToolEvent = (status: 'start' | 'done' | 'error', json: Record<string, unknown>) => {
    const toolId = String(json.toolCallId ?? json.id ?? '');
    const name = String(json.name ?? json.tool ?? '工具');
    // 后端对同一工具调用会发两次 tool_call_start（一次无参数、一次带参数），按 toolId 去重避免重复卡片
    setTools((prev) => {
      const exist = prev.find((t) => t.id === toolId);
      if (status === 'start') {
        if (exist) return prev.map((t) => (t.id === toolId ? { ...t, name: name || t.name, status: 'start' } : t));
        return [...prev, { id: toolId, name, status }];
      }
      return prev.map((t) => (t.id === toolId ? { ...t, status } : t));
    });
    // fill_form 完成 → 派发事件，宿主表单页监听后填充
    if (status === 'done' && name === 'fill_form' && json.result) {
      try {
        const data = JSON.parse(String(json.result)) as {
          kind?: string;
          values?: Record<string, unknown>;
          skipped?: string[];
        };
        if (data?.kind === 'fill_form' && data.values) {
          window.dispatchEvent(
            new CustomEvent('cube:ai-fill-form', { detail: { values: data.values, skipped: data.skipped ?? [] } }),
          );
        }
      } catch {
        // 解析失败忽略
      }
    }
  };

  const handleSend = async (prefill?: string) => {
    const text = (prefill ?? input).trim();
    if (!text || streaming) return;
    setInput('');
    setStreaming(true);

    // 用户消息需回显文本（转义后渲染），否则气泡为空、发送无反馈
    const userMsg: ChatMsg = { id: ++seq, type: 'user', html: escapeHtml(text) };
    const assistMsg: ChatMsg = { id: ++seq, type: 'assistant', html: '' };
    setMessages((prev) => [...prev, userMsg, assistMsg]);
    let full = '';

    const updateAssist = (html: string) => {
      setMessages((prev) => prev.map((m) => (m.id === assistMsg.id ? { ...m, html } : m)));
    };

    try {
      const token = api.tokenManager.getToken();
      const resp = await fetch('/Ai/AiChat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({
          sessionId: sessionIdRef.current,
          message: text,
          page: pageKind,
          mode: isEdit ? 'edit' : 'add',
          id: recordId,
          query: '',
          area: targetArea,
          controller: targetController,
          url: location.pathname,
          think,
        }),
      });
      if (!resp.ok) {
        // 非 2xx：读 JSON 或纯文本错误
        const body = await resp.text();
        let msg = `HTTP ${resp.status}`;
        if (body) {
          try {
            const data = JSON.parse(body) as { message?: string };
            if (data?.message) msg = data.message;
          } catch {
            // 非 JSON 响应体，保留 HTTP 状态码
          }
        }
        throw new Error(msg);
      }

      // 区分 SSE 与 JSON 错误：后端失败时返回 application/json（如 AISwitch 关闭），SSE 为 text/event-stream。
      // 若 HTTP 200 但非 SSE，整读 JSON 解析错误消息，避免"发消息无响应"静默吞错
      const ct = resp.headers.get('content-type') || '';
      if (!ct.includes('text/event-stream')) {
        const body = await resp.text();
        let msg = 'AI 请求失败';
        if (body) {
          try {
            const data = JSON.parse(body) as { message?: string };
            if (data?.message) msg = data.message;
          } catch {
            // 非 JSON 响应体，保留通用错误
          }
        }
        throw new Error(msg);
      }

      const reader = resp.body!.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';
        for (const line of lines) {
          const t = line.trim();
          if (!t.startsWith('data: ')) continue;
          let json: Record<string, unknown>;
          try {
            json = JSON.parse(t.substring(6)) as Record<string, unknown>;
          } catch {
            continue;
          }
          if (!json) continue;
          if (json.type === 'content_delta') {
            full += String(json.content ?? '');
            updateAssist(renderMarkdown(full));
            scrollBottom();
          } else if (json.type === 'tool_call_start') {
            handleToolEvent('start', json);
          } else if (json.type === 'tool_call_done') {
            handleToolEvent('done', json);
          } else if (json.type === 'tool_call_error') {
            handleToolEvent('error', json);
          } else if (json.type === 'run_js') {
            handleRunJs(json);
          } else if (json.type === 'error') {
            updateAssist(`<span style="color:var(--cube-danger)">⚠️ ${String(json.message ?? 'AI 调用失败')}</span>`);
            scrollBottom();
          }
          // message_start / message_done / thinking_delta / heartbeat 规范事件无需处理，忽略
        }
      }
    } catch (err) {
      updateAssist(
        `<span style="color:var(--cube-danger)">⚠️ ${(err as Error)?.message || '请求失败'}</span><br/><small>请确认 AI 服务已启用（系统设置中开启 AISwitch）</small>`,
      );
    } finally {
      setTools((prev) => prev.map((t) => (t.status === 'start' ? { ...t, status: 'error', name: t.name + '（中断）' } : t)));
      setStreaming(false);
      // 渲染 Mermaid 图表
      requestAnimationFrame(() => {
        if (bodyRef.current) renderMermaidBlocks(bodyRef.current, mermaidUrlRef.current);
      });
    }
  };

  /** 快捷指令：按页面类型一键任务 */
  const quickActions = useCallback((): { label: string; prompt: string }[] => {
    if (pageKind === 'form') {
      return [
        { label: '📝 帮我填表', prompt: '帮我填写当前表单' },
        ...(isEdit ? [{ label: '🔍 分析当前记录', prompt: '分析当前记录' }] : []),
        { label: '🩺 系统诊断', prompt: '检查系统运行状态' },
      ];
    }
    return [
      { label: '📊 分析当前数据', prompt: '分析当前列表数据' },
      { label: '🩺 系统诊断', prompt: '检查系统运行状态' },
    ];
  }, [pageKind, isEdit]);

  // AISwitch 关闭时不渲染（对齐 Vue v-if="enabled"）；hook 已全部在顶部，早退安全
  if (!enabled) return null;

  return (
    <>
      {/* 悬浮按钮 */}
      {!open && (
        <Tooltip title="AI 助手">
          <Button
            type="primary"
            className="cube-ai-fab"
            shape="circle"
            icon={<RobotOutlined />}
            onClick={() => setOpen(true)}
          />
        </Tooltip>
      )}

      {/* 对话面板 */}
      {open && (
        <div className={`cube-ai-panel${maximized ? ' maximized' : ''}`}>
          {/* 头部 */}
          <div className="cube-ai-header">
            <span className="cube-ai-header-title">
              <RobotOutlined /> AI 助手
              <span className="cube-ai-header-path">{location.pathname}</span>
            </span>
            <Space size={2}>
              <Button
                type="text"
                size="small"
                className="cube-ai-header-btn"
                title={maximized ? '还原' : '最大化'}
                icon={maximized ? <FullscreenExitOutlined /> : <FullscreenOutlined />}
                onClick={toggleMaximize}
              />
              <Button
                type="text"
                size="small"
                className="cube-ai-header-btn"
                title="清空会话"
                icon={<DeleteOutlined />}
                onClick={handleClear}
              />
              <Button type="text" size="small" className="cube-ai-header-close" icon={<CloseOutlined />} onClick={() => setOpen(false)} />
            </Space>
          </div>

          {/* 消息区 */}
          <div ref={bodyRef} className="cube-ai-body">
            {messages.length === 0 && (
              <div className="cube-ai-empty">
                <div className="cube-ai-empty-icon">
                  <RobotOutlined />
                </div>
                <p>我是 AI 助手，可以分析数据、填写表单、检查系统状态</p>
                <div className="cube-ai-quick">
                  {quickActions().map((q) => (
                    <Button key={q.prompt} size="small" onClick={() => void handleSend(q.prompt)}>
                      {q.label}
                    </Button>
                  ))}
                </div>
              </div>
            )}
            {messages.map((m) => (
              <div key={m.id} className={`cube-ai-row ${m.type === 'user' ? 'user' : ''}`}>
                <div
                  className={`cube-ai-bubble ${m.type === 'user' ? 'user' : 'assistant'}`}
                  dangerouslySetInnerHTML={{ __html: m.html || (m.type === 'assistant' && streaming ? '...' : '') }}
                />
              </div>
            ))}
            {/* 工具卡片 */}
            {tools.map((t) => (
              <div key={t.id} className="cube-ai-tool">
                {t.status === 'start' ? '⏳' : t.status === 'done' ? '✅' : '❌'} <b>{t.name}</b>{' '}
                {t.status === 'start' ? '调用中...' : t.status === 'done' ? '完成' : '失败'}
              </div>
            ))}
          </div>

          {/* 输入区 */}
          <div className="cube-ai-input">
            <div className="cube-ai-input-row">
              <Checkbox
                className="cube-ai-think"
                checked={think}
                onChange={(e) => setThink(e.target.checked)}
                title="深度推理更准确，但耗时更长"
              >
                深度
              </Checkbox>
              <Space.Compact style={{ flex: 1 }}>
                <Input
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onPressEnter={() => void handleSend()}
                  placeholder="输入问题，Enter 发送"
                  disabled={streaming}
                />
                <Button type="primary" icon={<SendOutlined />} loading={streaming} onClick={() => void handleSend()} />
              </Space.Compact>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
