// NewLife.Cube.TDesign/web/src/components/FieldInput.vue
<template>
  <t-switch v-if="wt === 'switch'" :value="!!modelValue" @change="(v: boolean) => emit('update:modelValue', v)" />
  <t-select v-else-if="wt === 'select'"
    :value="modelValue" @change="(v: any) => emit('update:modelValue', v)"
    :placeholder="'请选择' + (field.displayName || field.name)" clearable style="width: 100%">
    <t-option v-for="opt in options" :key="opt.value" :value="opt.value" :label="opt.label" />
  </t-select>
  <t-input-number v-else-if="wt === 'number'"
    :value="modelValue" @change="(v: number) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" theme="normal" style="width: 100%" />
  <t-date-picker v-else-if="wt === 'datetime'"
    :value="modelValue" @change="(v: any) => emit('update:modelValue', v)"
    enable-time-picker :placeholder="'请选择' + (field.displayName || field.name)" style="width: 100%" />
  <t-date-picker v-else-if="wt === 'date'"
    :value="modelValue" @change="(v: any) => emit('update:modelValue', v)"
    :placeholder="'请选择' + (field.displayName || field.name)" style="width: 100%" />
  <t-textarea v-else-if="wt === 'textarea' || wt === 'html'"
    :value="modelValue" @change="(v: string) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" :autosize="{ minRows: 3 }" />
  <t-input v-else-if="wt === 'password'" type="password"
    :value="modelValue" @change="(v: string) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" />
  <span v-else-if="wt === 'readonly'" style="color: var(--td-text-color-secondary)">{{ modelValue ?? '-' }}</span>
  <t-input v-else
    :value="modelValue" @change="(v: string) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { DataField } from '@cube/api-core';
import { resolveWidget } from '@cube/field-mapping';

const props = defineProps<{ field: DataField; modelValue: any }>();
const emit = defineEmits<{ 'update:modelValue': [v: any] }>();

const wt = computed(() => resolveWidget(props.field).widget);

const options = computed(() => {
  if (!props.field.dataSource) return [];
  return Object.entries(props.field.dataSource).map(([value, label]) => ({ value, label }));
});
</script>

// NewLife.Cube.Shadcn/web/src/components/FieldInput.tsx
import { type ReactNode } from 'react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import type { FieldMapping } from '@cube/field-mapping';

interface FieldInputProps {
  mapping: FieldMapping;
  value: any;
  onChange: (value: any) => void;
}

export default function FieldInput({ mapping, value, onChange }: FieldInputProps): ReactNode {
  const { widget, field } = mapping;
  const label = field.displayName ?? field.name;

  switch (widget) {
    case 'number':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="number" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} required={field.required} />
        </div>
      );

    case 'switch':
      return (
        <div className="flex items-center gap-2">
          <Switch checked={!!value} onCheckedChange={(v) => onChange(v)} disabled={field.readOnly} id={field.name} />
          <Label htmlFor={field.name}>{label}</Label>
        </div>
      );

    case 'select': {
      const ds = field.dataSource ?? {};
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Select value={String(value ?? '')} onValueChange={onChange} disabled={field.readOnly}>
            <SelectTrigger><SelectValue placeholder="请选择" /></SelectTrigger>
            <SelectContent>
              {Object.entries(ds).map(([k, v]) => (
                <SelectItem key={k} value={k}>{v}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      );
    }

    case 'datetime':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="datetime-local" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} />
        </div>
      );

    case 'date':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="date" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} />
        </div>
      );

    case 'textarea':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Textarea rows={4} value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} required={field.required} />
        </div>
      );

    case 'password':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="password" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} />
        </div>
      );

    case 'email':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="email" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} />
        </div>
      );

    case 'phone':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="tel" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} />
        </div>
      );

    case 'url':
    case 'link':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="url" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} />
        </div>
      );

    case 'color':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="color" value={value ?? '#000000'} onChange={(e) => onChange(e.target.value)} className="h-9 w-16 p-1" />
        </div>
      );

    case 'image':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="file" accept="image/*" onChange={(e: any) => onChange(e.target.files?.[0])} disabled={field.readOnly} />
        </div>
      );

    case 'file':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input type="file" onChange={(e: any) => onChange(e.target.files?.[0])} disabled={field.readOnly} />
        </div>
      );

    case 'code':
    case 'html':
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Textarea rows={8} className="font-mono text-xs" value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} />
        </div>
      );

    default:
      return (
        <div className="space-y-1">
          <Label>{label}</Label>
          <Input value={value ?? ''} onChange={(e) => onChange(e.target.value)} disabled={field.readOnly} required={field.required} />
        </div>
      );
  }
}
