// NewLife.Cube.Angular/web/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzDividerModule } from 'ng-zorro-antd/divider';
import { NzMessageService } from 'ng-zorro-antd/message';
import type { OAuthProvider } from '@cube/api-core';
import { ApiService } from '../../services/api.service';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, NzCardModule, NzFormModule, NzInputModule, NzButtonModule, NzDividerModule],
  template: `
    <div style="display: flex; justify-content: center; align-items: center; min-height: 100vh; background: linear-gradient(135deg, #1890ff 0%, #722ed1 100%);">
      <nz-card style="width: 400px;" [nzBordered]="false">
        <div style="text-align: center; font-size: 20px; font-weight: bold; margin-bottom: 24px;">登录</div>
        <form nz-form (ngSubmit)="handleLogin()">
          <nz-form-item>
            <nz-form-label>用户名</nz-form-label>
            <nz-form-control>
              <input nz-input [(ngModel)]="username" name="username" placeholder="请输入用户名" />
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-label>密码</nz-form-label>
            <nz-form-control>
              <input nz-input type="password" [(ngModel)]="password" name="password" placeholder="请输入密码" />
            </nz-form-control>
          </nz-form-item>
          <button nz-button nzType="primary" nzBlock nzSize="large" [nzLoading]="loading">登录</button>
        </form>
        @if (oauthProviders.length) {
          <nz-divider nzText="第三方登录"></nz-divider>
          <div style="display: flex; gap: 8px; justify-content: center;">
            @for (p of oauthProviders; track p.name) {
              <button nz-button (click)="oauthLogin(p.name)">{{ p.displayName || p.name }}</button>
            }
          </div>
        }
      </nz-card>
    </div>
  `,
})
export class LoginComponent implements OnInit {
  username = '';
  password = '';
  loading = false;
  oauthProviders: OAuthProvider[] = [];

  constructor(
    private api: ApiService,
    private userService: UserService,
    private router: Router,
    private message: NzMessageService,
  ) {}

  async ngOnInit() {
    const res = await this.api.config.getLoginConfig();
    if (res.data?.providers) this.oauthProviders = res.data.providers;
  }

  async handleLogin() {
    if (!this.username || !this.password) {
      this.message.warning('请输入用户名和密码');
      return;
    }
    this.loading = true;
    try {
      const res = await this.userService.login(this.username, this.password);
      if (res.data) {
        this.message.success('登录成功');
        this.router.navigate(['/home']);
      } else {
        this.message.error(res.message || '登录失败');
      }
    } finally {
      this.loading = false;
    }
  }

  oauthLogin(name: string) {
    window.location.href = `/Sso/LoginExternal?provider=${name}`;
  }
}

// NewLife.Cube.ArcoVue/web/src/views/login/index.vue
<template>
  <div style="display: flex; justify-content: center; align-items: center; min-height: 100vh; background: linear-gradient(135deg, #165DFF 0%, #722ED1 100%);">
    <a-card style="width: 400px;" :bordered="false">
      <template #title>
        <div style="text-align: center; font-size: 20px; font-weight: bold;">登录</div>
      </template>
      <a-form :model="form" @submit="handleLogin" layout="vertical">
        <a-form-item field="username" label="用户名">
          <a-input v-model="form.username" placeholder="请输入用户名" allow-clear />
        </a-form-item>
        <a-form-item field="password" label="密码">
          <a-input-password v-model="form.password" placeholder="请输入密码" allow-clear />
        </a-form-item>
        <a-form-item>
          <a-button type="primary" html-type="submit" long :loading="loading">登录</a-button>
        </a-form-item>
      </a-form>
      <a-divider v-if="oauthProviders.length">第三方登录</a-divider>
      <div v-if="oauthProviders.length" style="display: flex; gap: 8px; justify-content: center;">
        <a-button v-for="p in oauthProviders" :key="p.name" @click="oauthLogin(p.name)">
          {{ p.displayName || p.name }}
        </a-button>
      </div>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { Message } from '@arco-design/web-vue';
import type { OAuthProvider } from '@cube/api-core';
import cubeApi from '@/api';
import { useUserStore } from '@/stores/user';

const router = useRouter();
const userStore = useUserStore();

const form = reactive({ username: '', password: '' });
const loading = ref(false);
const oauthProviders = ref<OAuthProvider[]>([]);

onMounted(async () => {
  const res = await cubeApi.config.getLoginConfig();
  if (res.data?.providers) oauthProviders.value = res.data.providers;
});

async function handleLogin() {
  if (!form.username || !form.password) {
    Message.warning('请输入用户名和密码');
    return;
  }
  loading.value = true;
  try {
    const res = await userStore.login(form.username, form.password);
    if (res.data) {
      Message.success('登录成功');
      router.push('/home');
    } else {
      Message.error(res.message || '登录失败');
    }
  } finally {
    loading.value = false;
  }
}

function oauthLogin(name: string) {
  window.location.href = `/Sso/LoginExternal?provider=${name}`;
}
</script>
