// NewLife.Cube.ArcoVue/web/src/views/login/index.vue
<template>
  <div class="login-wrap">
    <a-card class="login-card" :bordered="false">
      <div class="login-header">
        <img v-if="logoSrc" :src="logoSrc" class="login-logo" alt="" />
        <h2>{{ siteInfo?.displayName || '魔方管理平台' }}</h2>
        <p v-if="loginConfig?.loginTip" class="login-tip">{{ loginConfig.loginTip }}</p>
      </div>

      <a-tabs v-model:active-key="activeTab">
        <!-- 密码登录 -->
        <a-tab-pane v-if="loginConfig?.allowLogin !== false" key="password" title="密码登录">
          <a-form :model="form" @submit="handleLogin" layout="vertical">
            <a-form-item field="username" label="用户名">
              <a-input v-model="form.username" placeholder="请输入用户名" allow-clear />
            </a-form-item>
            <a-form-item field="password" label="密码">
              <a-input-password v-model="form.password" placeholder="请输入密码" allow-clear />
            </a-form-item>
            <a-form-item>
              <a-button type="primary" html-type="submit" long :loading="loading">登录</a-button>
            </a-form-item>
          </a-form>
        </a-tab-pane>

        <!-- 手机验证码登录 -->
        <a-tab-pane v-if="loginConfig?.enableSms" key="sms" title="手机验证码">
          <a-form :model="codeForm" layout="vertical">
            <a-form-item label="手机号">
              <a-input v-model="codeForm.username" placeholder="请输入手机号" allow-clear />
            </a-form-item>
            <a-form-item label="验证码">
              <a-input-group>
                <a-input v-model="codeForm.code" placeholder="请输入验证码" style="flex: 1" allow-clear />
                <a-button :disabled="smsCountdown > 0" @click="sendCode('Sms')">
                  {{ smsCountdown > 0 ? `${smsCountdown}s 后重发` : '获取验证码' }}
                </a-button>
              </a-input-group>
            </a-form-item>
            <a-form-item>
              <a-button type="primary" long :loading="codeLoading" @click="handleCodeLogin(1)">登录</a-button>
            </a-form-item>
          </a-form>
        </a-tab-pane>

        <!-- 邮箱验证码登录 -->
        <a-tab-pane v-if="loginConfig?.enableMail" key="email" title="邮箱验证码">
          <a-form :model="emailForm" layout="vertical">
            <a-form-item label="邮箱">
              <a-input v-model="emailForm.username" placeholder="请输入邮箱地址" allow-clear />
            </a-form-item>
            <a-form-item label="验证码">
              <a-input-group>
                <a-input v-model="emailForm.code" placeholder="请输入验证码" style="flex: 1" allow-clear />
                <a-button :disabled="mailCountdown > 0" @click="sendCode('Mail', emailForm.username)">
                  {{ mailCountdown > 0 ? `${mailCountdown}s 后重发` : '获取验证码' }}
                </a-button>
              </a-input-group>
            </a-form-item>
            <a-form-item>
              <a-button type="primary" long :loading="mailLoading" @click="handleCodeLogin(2, emailForm)">登录</a-button>
            </a-form-item>
          </a-form>
        </a-tab-pane>
      </a-tabs>

      <!-- OAuth 第三方登录 -->
      <template v-if="oauthProviders.length">
        <a-divider>第三方登录</a-divider>
        <div class="oauth-list">
          <a
            v-for="p in oauthProviders"
            :key="p.name"
            class="oauth-item"
            :title="p.nickName || p.name"
            @click="oauthLogin(p.name)"
          >
            <img v-if="p.logo" :src="p.logo" class="oauth-logo" :alt="p.nickName || p.name" />
            <span v-else class="oauth-fallback">{{ (p.nickName || p.name).charAt(0).toUpperCase() }}</span>
            <span class="oauth-name">{{ p.nickName || p.name }}</span>
          </a>
        </div>
      </template>

      <!-- 注册入口 -->
      <div v-if="loginConfig?.allowRegister" class="register-link">
        <span>还没有账号？</span>
        <a-link @click="router.push('/register')">立即注册</a-link>
      </div>

      <!-- 忘记密码 -->
      <div class="forgot-link">
        <a-link @click="router.push('/forgot-password')">忘记密码？</a-link>
      </div>

      <!-- 版权信息 -->
      <div v-if="siteInfo?.copyright || siteInfo?.registration" class="login-footer">
        <div v-if="siteInfo?.copyright" v-html="siteInfo.copyright" class="login-copyright"></div>
        <div v-if="siteInfo?.registration">
          <a href="https://www.beianx.cn/" target="_blank" rel="noopener noreferrer">{{ siteInfo.registration }}</a>
        </div>
      </div>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, onMounted, computed } from 'vue';
import { useRouter } from 'vue-router';
import { Message } from '@arco-design/web-vue';
import type { OAuthProvider, SiteInfo, LoginConfig } from '@cube/api-core';
import cubeApi from '@/api';
import { useUserStore } from '@/stores/user';

const router = useRouter();
const userStore = useUserStore();

const form = reactive({ username: '', password: '' });
const codeForm = reactive({ username: '', code: '' });
const emailForm = reactive({ username: '', code: '' });
const loading = ref(false);
const codeLoading = ref(false);
const mailLoading = ref(false);
const smsCountdown = ref(0);
const mailCountdown = ref(0);
const activeTab = ref('password');
const oauthProviders = ref<OAuthProvider[]>([]);
const loginConfig = ref<LoginConfig | null>(null);
const siteInfo = ref<SiteInfo | null>(null);

const logoSrc = computed(() => siteInfo.value?.loginLogo || loginConfig.value?.logo || '');

onMounted(async () => {
  try {
    const [siteRes, configRes] = await Promise.all([
      cubeApi.user.getSiteInfo(),
      cubeApi.user.getLoginConfig(),
    ]);
    siteInfo.value = siteRes.data;
    loginConfig.value = configRes.data;
    oauthProviders.value = configRes.data?.providers ?? [];
    // 自动切换到第一个可用 tab
    if (configRes.data?.allowLogin === false) {
      if (configRes.data.enableSms) activeTab.value = 'sms';
      else if (configRes.data.enableMail) activeTab.value = 'email';
    }
  } catch { /* ignore */ }
});

async function handleLogin() {
  if (!form.username || !form.password) {
    Message.warning('请输入用户名和密码');
    return;
  }
  loading.value = true;
  try {
    const res = await userStore.login(form.username, form.password);
    if (res.data) {
      Message.success('登录成功');
      router.push('/home');
    } else {
      Message.error(res.message || '登录失败');
    }
  } finally {
    loading.value = false;
  }
}

async function sendCode(channel: 'Sms' | 'Mail', username?: string) {
  const name = username ?? codeForm.username;
  if (!name) {
    Message.warning(channel === 'Sms' ? '请输入手机号' : '请输入邮箱地址');
    return;
  }
  try {
    await cubeApi.user.sendCode({ channel, username: name, action: 'login' });
    Message.success(channel === 'Sms' ? '验证码已发送' : '验证码已发送至您的邮箱');
    const countRef = channel === 'Sms' ? smsCountdown : mailCountdown;
    countRef.value = 60;
    const timer = setInterval(() => {
      countRef.value--;
      if (countRef.value <= 0) clearInterval(timer);
    }, 1000);
  } catch (err: any) {
    Message.error(err?.message || '发送失败');
  }
}

async function handleCodeLogin(loginCategory: 1 | 2, formData?: { username: string; code: string }) {
  const data = formData ?? codeForm;
  const loadingRef = loginCategory === 1 ? codeLoading : mailLoading;
  if (!data.username) {
    Message.warning(loginCategory === 1 ? '请输入手机号' : '请输入邮箱地址');
    return;
  }
  if (!data.code) {
    Message.warning('请输入验证码');
    return;
  }
  loadingRef.value = true;
  try {
    const res = await cubeApi.user.loginByCode({ username: data.username, password: data.code, loginCategory });
    if (res.data?.accessToken) {
      cubeApi.tokenManager.setToken(res.data.accessToken);
      await userStore.fetchUserInfo();
      await userStore.fetchMenus();
    }
    Message.success('登录成功');
    router.push('/home');
  } catch (err: any) {
    Message.error(err?.message || '登录失败');
  } finally {
    loadingRef.value = false;
  }
}

function oauthLogin(name: string) {
  window.location.href = `/Sso/Login/${name}?r=${encodeURIComponent(new URLSearchParams(window.location.search).get('redirect') || '/')}`;
}
</script>

<style scoped>
.login-wrap {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #165dff 0%, #722ed1 100%);
}
.login-card {
  width: 440px;
  border-radius: 8px;
}
.login-header {
  text-align: center;
  margin-bottom: 16px;
}
.login-logo {
  width: 52px;
  height: 52px;
  margin-bottom: 8px;
}
.login-header h2 {
  margin: 0 0 4px;
  font-size: 20px;
}
.login-tip {
  color: #999;
  font-size: 13px;
  margin: 0;
}
.oauth-list {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  justify-content: center;
  margin-top: 8px;
}
.oauth-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  cursor: pointer;
  color: inherit;
  text-decoration: none;
}
.oauth-item:hover .oauth-name {
  color: var(--primary-6, #165dff);
}
.oauth-logo {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  object-fit: contain;
}
.oauth-fallback {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  background: #e4e6f0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 16px;
  font-weight: 600;
}
.oauth-name {
  font-size: 12px;
  margin-top: 4px;
  max-width: 56px;
  text-align: center;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.register-link {
  text-align: center;
  margin-top: 12px;
  font-size: 13px;
  color: #86909c;
}
.login-footer {
  text-align: center;
  margin-top: 16px;
  font-size: 12px;
  color: #86909c;
}
.login-footer a {
  color: #86909c;
  text-decoration: none;
}
.login-footer a:hover {
  color: var(--primary-6, #165dff);
}
</style>

// NewLife.Cube.Shadcn/web/src/pages/login/Login.tsx
import { useState, useEffect, type FormEvent } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useUserStore } from '@/stores/user';
import api from '@/api';
import type { LoginConfig, SiteInfo } from '@cube/api-core';

export default function Login() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const { login } = useUserStore();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [smsUsername, setSmsUsername] = useState('');
  const [smsCode, setSmsCode] = useState('');
  const [mailUsername, setMailUsername] = useState('');
  const [mailCode, setMailCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [codeLoading, setCodeLoading] = useState(false);
  const [mailLoading, setMailLoading] = useState(false);
  const [smsCountdown, setSmsCountdown] = useState(0);
  const [mailCountdown, setMailCountdown] = useState(0);
  const [error, setError] = useState('');
  const [config, setConfig] = useState<LoginConfig | null>(null);
  const [siteInfo, setSiteInfo] = useState<SiteInfo | null>(null);
  const [activeTab, setActiveTab] = useState('password');

  useEffect(() => {
    Promise.all([api.user.getLoginConfig(), api.user.getSiteInfo()])
      .then(([configRes, siteRes]) => {
        setConfig(configRes.data);
        setSiteInfo(siteRes.data);
        if (configRes.data?.allowLogin === false) {
          if (configRes.data.enableSms) setActiveTab('sms');
          else if (configRes.data.enableMail) setActiveTab('email');
        }
      })
      .catch(() => {});
  }, []);

  const startCountdown = (type: 'sms' | 'mail') => {
    const setter = type === 'sms' ? setSmsCountdown : setMailCountdown;
    setter(60);
    const timer = setInterval(() => {
      setter((v) => {
        if (v <= 1) { clearInterval(timer); return 0; }
        return v - 1;
      });
    }, 1000);
  };

  const handleSendCode = async (channel: 'Sms' | 'Mail') => {
    const name = channel === 'Sms' ? smsUsername : mailUsername;
    if (!name) { setError(channel === 'Sms' ? '请输入手机号' : '请输入邮箱地址'); return; }
    setError('');
    try {
      await api.user.sendCode({ channel, username: name, action: 'login' });
      startCountdown(channel === 'Sms' ? 'sms' : 'mail');
    } catch (err: any) {
      setError(err?.message ?? '发送失败');
    }
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!username || !password) { setError('请输入用户名和密码'); return; }
    setLoading(true);
    setError('');
    try {
      await login(username, password);
      navigate(params.get('redirect') ?? '/', { replace: true });
    } catch (err: any) {
      setError(err?.message ?? '登录失败');
    } finally {
      setLoading(false);
    }
  };

  const handleCodeLogin = async (loginCategory: 1 | 2) => {
    const name = loginCategory === 1 ? smsUsername : mailUsername;
    const code = loginCategory === 1 ? smsCode : mailCode;
    const setLoad = loginCategory === 1 ? setCodeLoading : setMailLoading;
    if (!name) { setError(loginCategory === 1 ? '请输入手机号' : '请输入邮箱地址'); return; }
    if (!code) { setError('请输入验证码'); return; }
    setLoad(true);
    setError('');
    try {
      const res = await api.user.loginByCode({ username: name, password: code, loginCategory });
      if (res.data?.accessToken) api.tokenManager.setToken(res.data.accessToken);
      navigate(params.get('redirect') ?? '/', { replace: true });
    } catch (err: any) {
      setError(err?.message ?? '登录失败');
    } finally {
      setLoad(false);
    }
  };

  const logoSrc = siteInfo?.loginLogo || config?.logo || '';

  const hasTabs = (config?.allowLogin !== false ? 1 : 0) + (config?.enableSms ? 1 : 0) + (config?.enableMail ? 1 : 0) > 1;

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-indigo-500 to-purple-600 p-4">
      <div className="w-full max-w-sm rounded-lg border bg-card p-8 shadow-xl">
        {/* Logo + 标题 */}
        <div className="mb-6 text-center">
          {logoSrc && <img src={logoSrc} alt="logo" className="mx-auto mb-2 h-16 w-16 rounded-full object-contain" />}
          <h1 className="text-2xl font-bold text-card-foreground">{siteInfo?.displayName ?? config?.displayName ?? '魔方管理平台'}</h1>
          {config?.loginTip && <p className="mt-1 text-sm text-muted-foreground">{config.loginTip}</p>}
        </div>

        {error && (
          <div className="mb-4 rounded-md border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </div>
        )}

        {hasTabs ? (
          <div>
            {/* Tab 导航栏 */}
            <div className="flex rounded-lg bg-muted p-1 mb-4">
              {config?.allowLogin !== false && (
                <button type="button"
                  className={`flex-1 rounded-md px-3 py-1.5 text-sm font-medium transition-all ${activeTab === 'password' ? 'bg-background shadow text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
                  onClick={() => setActiveTab('password')}>密码登录</button>
              )}
              {config?.enableSms && (
                <button type="button"
                  className={`flex-1 rounded-md px-3 py-1.5 text-sm font-medium transition-all ${activeTab === 'sms' ? 'bg-background shadow text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
                  onClick={() => setActiveTab('sms')}>手机验证码</button>
              )}
              {config?.enableMail && (
                <button type="button"
                  className={`flex-1 rounded-md px-3 py-1.5 text-sm font-medium transition-all ${activeTab === 'email' ? 'bg-background shadow text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
                  onClick={() => setActiveTab('email')}>邮箱验证码</button>
              )}
            </div>

            {/* 密码登录 */}
            {activeTab === 'password' && config?.allowLogin !== false && (
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="username">用户名</Label>
                  <Input id="username" autoFocus value={username} onChange={(e) => setUsername(e.target.value)} placeholder="请输入用户名" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="password">密码</Label>
                  <Input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="请输入密码" />
                </div>
                <Button type="submit" className="w-full" disabled={loading}>{loading ? '登录中...' : '登 录'}</Button>
              </form>
            )}

            {/* 手机验证码 */}
            {activeTab === 'sms' && config?.enableSms && (
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label>手机号</Label>
                  <Input value={smsUsername} onChange={(e) => setSmsUsername(e.target.value)} placeholder="请输入手机号" />
                </div>
                <div className="space-y-2">
                  <Label>验证码</Label>
                  <div className="flex gap-2">
                    <Input value={smsCode} onChange={(e) => setSmsCode(e.target.value)} placeholder="请输入验证码" />
                    <Button type="button" variant="outline" disabled={smsCountdown > 0} onClick={() => handleSendCode('Sms')}>
                      {smsCountdown > 0 ? `${smsCountdown}s` : '获取验证码'}
                    </Button>
                  </div>
                </div>
                <Button className="w-full" disabled={codeLoading} onClick={() => handleCodeLogin(1)}>
                  {codeLoading ? '登录中...' : '登 录'}
                </Button>
              </div>
            )}

            {/* 邮箱验证码 */}
            {activeTab === 'email' && config?.enableMail && (
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label>邮箱地址</Label>
                  <Input type="email" value={mailUsername} onChange={(e) => setMailUsername(e.target.value)} placeholder="请输入邮箱地址" />
                </div>
                <div className="space-y-2">
                  <Label>验证码</Label>
                  <div className="flex gap-2">
                    <Input value={mailCode} onChange={(e) => setMailCode(e.target.value)} placeholder="请输入验证码" />
                    <Button type="button" variant="outline" disabled={mailCountdown > 0} onClick={() => handleSendCode('Mail')}>
                      {mailCountdown > 0 ? `${mailCountdown}s` : '获取验证码'}
                    </Button>
                  </div>
                </div>
                <Button className="w-full" disabled={mailLoading} onClick={() => handleCodeLogin(2)}>
                  {mailLoading ? '登录中...' : '登 录'}
                </Button>
              </div>
            )}
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="username">用户名</Label>
              <Input id="username" autoFocus value={username} onChange={(e) => setUsername(e.target.value)} placeholder="请输入用户名" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">密码</Label>
              <Input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="请输入密码" />
            </div>
            <Button type="submit" className="w-full" disabled={loading}>{loading ? '登录中...' : '登 录'}</Button>
          </form>
        )}

        {/* OAuth 第三方登录 */}
        {config?.providers?.length ? (
          <>
            <div className="relative my-4">
              <div className="absolute inset-0 flex items-center"><span className="w-full border-t" /></div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-card px-2 text-muted-foreground">其他登录方式</span>
              </div>
            </div>
            <div className="flex flex-wrap justify-center gap-3">
              {config.providers.map((p) => (
                <div key={p.name} className="flex flex-col items-center gap-1 cursor-pointer"
                  title={p.nickName ?? p.name}
                  onClick={() => { const redirect = new URLSearchParams(window.location.search).get('redirect') || '/'; window.location.href = `/Sso/Login/${p.name}?r=${encodeURIComponent(redirect)}`; }}
                >
                  {p.logo
                    ? <img src={p.logo} alt="" className="h-9 w-9 rounded-full object-contain" />
                    : <span className="flex h-9 w-9 items-center justify-center rounded-full bg-muted text-base font-semibold">
                        {(p.nickName ?? p.name).charAt(0).toUpperCase()}
                      </span>
                  }
                  <span className="max-w-[56px] overflow-hidden text-ellipsis whitespace-nowrap text-xs text-muted-foreground">
                    {p.nickName ?? p.name}
                  </span>
                </div>
              ))}
            </div>
          </>
        ) : null}

        {/* 注册入口 */}
        {config?.allowRegister && (
          <p className="mt-4 text-center text-sm text-muted-foreground">
            还没有账号？{' '}
            <button className="text-primary underline-offset-4 hover:underline" onClick={() => navigate('/register')}>立即注册</button>
          </p>
        )}

        {/* 忘记密码入口 */}
        <p className="mt-2 text-center text-sm">
          <button className="text-primary underline-offset-4 hover:underline" onClick={() => navigate('/forgot-password')}>忘记密码？</button>
        </p>

        {/* 版权信息 */}
        {(siteInfo?.copyright || siteInfo?.registration) && (
          <div className="mt-4 text-center text-xs text-muted-foreground">
            {siteInfo.copyright && <div dangerouslySetInnerHTML={{ __html: siteInfo.copyright }} />}
            {siteInfo.registration && (
              <a href="https://www.beianx.cn/" target="_blank" rel="noopener noreferrer" className="hover:underline">
                {siteInfo.registration}
              </a>
            )}
          </div>
        )}
      </div>
    </div>
  );
}


export default function Login() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const { login } = useUserStore();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [config, setConfig] = useState<LoginConfig | null>(null);

  useEffect(() => {
    api.user.getLoginConfig().then((res) => setConfig(res.data)).catch(() => {});
  }, []);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!username || !password) { setError('请输入用户名和密码'); return; }
    setLoading(true);
    setError('');
    try {
      await login(username, password);
      navigate(params.get('redirect') ?? '/', { replace: true });
    } catch (err: any) {
      setError(err?.message ?? '登录失败');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-indigo-500 to-purple-600 p-4">
      <div className="w-full max-w-sm rounded-lg border bg-card p-8 shadow-xl">
        <div className="mb-6 text-center">
          {config?.logo && <img src={config.logo} alt="logo" className="mx-auto mb-2 h-16 w-16 rounded-full" />}
          <h1 className="text-2xl font-bold text-card-foreground">{config?.displayName ?? '魔方管理平台'}</h1>
          {config?.loginTip && <p className="mt-1 text-sm text-muted-foreground">{config.loginTip}</p>}
        </div>

        {error && (
          <div className="mb-4 rounded-md border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="username">用户名</Label>
            <Input id="username" autoFocus value={username} onChange={(e) => setUsername(e.target.value)} placeholder="请输入用户名" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">密码</Label>
            <Input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="请输入密码" />
          </div>
          <Button type="submit" className="w-full" disabled={loading}>
            {loading ? '登录中...' : '登 录'}
          </Button>
        </form>

        {config?.providers?.length ? (
          <>
            <div className="relative my-4">
              <div className="absolute inset-0 flex items-center"><span className="w-full border-t" /></div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-card px-2 text-muted-foreground">其他登录方式</span>
              </div>
            </div>
            <div className="flex flex-wrap justify-center gap-2">
              {config.providers.map((p) => (
                <Button key={p.name} variant="outline" size="sm"
                  onClick={() => { window.location.href = `/Sso/Login?provider=${encodeURIComponent(p.name)}`; }}
                >
                  {p.logo && <img src={p.logo} alt="" className="mr-1 h-4 w-4" />}
                  {p.nickName ?? p.name}
                </Button>
              ))}
            </div>
          </>
        ) : null}
      </div>
    </div>
  );
}
