// NewLife.Cube.Vuetify/web/src/views/home/index.vue
<template>
  <div>
    <div class="text-h5 font-weight-bold mb-4">首页</div>
    <v-row>
      <v-col v-for="card in stats" :key="card.title" cols="12" sm="6" md="3">
        <v-card>
          <v-card-text>
            <div class="text-body-2 text-medium-emphasis">{{ card.title }}</div>
            <div class="text-h4 font-weight-bold mt-1">{{ card.value }}</div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const stats = ref([
  { title: '用户总数', value: 0 },
  { title: '今日访问', value: 0 },
  { title: '在线用户', value: 0 },
  { title: '系统消息', value: 0 },
]);
</script>

// NewLife.Cube.Shadcn/web/src/pages/home/Home.tsx
export default function Home() {
  const stats = [
    { title: '在线用户', value: '-' },
    { title: '今日访问', value: '-' },
    { title: '系统版本', value: '-' },
    { title: '运行时间', value: '-' },
  ];

  return (
    <div>
      <h1 className="text-2xl font-bold">首页</h1>
      <p className="mt-1 text-sm text-muted-foreground">欢迎使用魔方管理平台</p>
      <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((s) => (
          <div key={s.title} className="rounded-lg border bg-card p-6">
            <p className="text-sm text-muted-foreground">{s.title}</p>
            <p className="mt-2 text-3xl font-bold">{s.value}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
