// NewLife.Cube.Shadcn/web/src/pages/home/Home.tsx
export default function Home() {
  const stats = [
    { title: '在线用户', value: '-' },
    { title: '今日访问', value: '-' },
    { title: '系统版本', value: '-' },
    { title: '运行时间', value: '-' },
  ];

  return (
    <div>
      <h1 className="text-2xl font-bold">首页</h1>
      <p className="mt-1 text-sm text-muted-foreground">欢迎使用魔方管理平台</p>
      <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((s) => (
          <div key={s.title} className="rounded-lg border bg-card p-6">
            <p className="text-sm text-muted-foreground">{s.title}</p>
            <p className="mt-2 text-3xl font-bold">{s.value}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

// NewLife.Cube.NaiveUI/web/src/views/home/index.vue
<template>
  <div class="home-page">
    <n-page-header title="首页" subtitle="欢迎使用魔方管理平台" />
    <n-grid :cols="4" :x-gap="16" :y-gap="16" style="margin-top: 16px">
      <n-gi v-for="card in statCards" :key="card.title">
        <n-card>
          <n-statistic :label="card.title" :value="card.value" />
        </n-card>
      </n-gi>
    </n-grid>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const statCards = ref([
  { title: '在线用户', value: '-' },
  { title: '今日访问', value: '-' },
  { title: '系统版本', value: '-' },
  { title: '运行时间', value: '-' },
]);
</script>

<style scoped>
.home-page {
  padding: 8px;
}
</style>
