// NewLife.Cube.ArcoVue/web/src/components/FieldInput.vue
<template>
  <component :is="renderField" />
</template>

<script setup lang="ts">
import { computed, h } from 'vue';
import type { DataField } from '@cube/api-core';
import { resolveWidget, type WidgetType } from '@cube/field-mapping';
import {
  Input as AInput,
  InputNumber as AInputNumber,
  InputPassword as AInputPassword,
  Select as ASelect,
  Switch as ASwitch,
  Textarea as ATextarea,
  DatePicker as ADatePicker,
} from '@arco-design/web-vue';

const props = defineProps<{
  field: DataField;
  value?: any;
}>();

const emit = defineEmits<{
  (e: 'update:value', v: any): void;
}>();

const widgetType = computed(() => resolveWidget(props.field).widget);

const renderField = computed(() => {
  const val = props.value;
  const onUpdate = (v: any) => emit('update:value', v);

  switch (widgetType.value) {
    case WidgetType.Switch:
      return h(ASwitch, { modelValue: !!val, 'onUpdate:modelValue': onUpdate });

    case WidgetType.Select:
    case WidgetType.TagList: {
      const options = parseOptions(props.field);
      return h(ASelect, {
        modelValue: val,
        'onUpdate:modelValue': onUpdate,
        placeholder: `请选择${props.field.displayName || props.field.name}`,
        allowClear: true,
        options,
      });
    }

    case WidgetType.Number:
    case WidgetType.Decimal:
      return h(AInputNumber, {
        modelValue: val,
        'onUpdate:modelValue': onUpdate,
        placeholder: `请输入${props.field.displayName || props.field.name}`,
        precision: widgetType.value === WidgetType.Decimal ? (props.field.precision || 2) : 0,
      });

    case WidgetType.DateTime:
    case WidgetType.Date:
      return h(ADatePicker, {
        modelValue: val,
        'onUpdate:modelValue': onUpdate,
        showTime: widgetType.value === WidgetType.DateTime,
        placeholder: `请选择${props.field.displayName || props.field.name}`,
        allowClear: true,
        style: 'width: 100%',
      });

    case WidgetType.TextArea:
    case WidgetType.RichText:
    case WidgetType.Html:
    case WidgetType.Markdown:
      return h(ATextarea, {
        modelValue: val,
        'onUpdate:modelValue': onUpdate,
        placeholder: `请输入${props.field.displayName || props.field.name}`,
        autoSize: { minRows: 3 },
      });

    case WidgetType.Password:
      return h(AInputPassword, {
        modelValue: val,
        'onUpdate:modelValue': onUpdate,
        placeholder: `请输入${props.field.displayName || props.field.name}`,
      });

    case WidgetType.File:
    case WidgetType.Image:
      return h(AInput, {
        modelValue: val,
        'onUpdate:modelValue': onUpdate,
        placeholder: `请输入文件URL`,
      });

    case WidgetType.ReadOnly:
      return h('span', {}, val ?? '-');

    default:
      return h(AInput, {
        modelValue: val,
        'onUpdate:modelValue': onUpdate,
        placeholder: `请输入${props.field.displayName || props.field.name}`,
        allowClear: true,
      });
  }
});

function parseOptions(field: DataField) {
  if (!field.dataSource) return [];
  try {
    const map = JSON.parse(field.dataSource) as Record<string, string>;
    return Object.entries(map).map(([value, label]) => ({ value, label }));
  } catch {
    return [];
  }
}
</script>

// NewLife.Cube.Angular/web/src/app/components/field-input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzInputNumberModule } from 'ng-zorro-antd/input-number';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzSwitchModule } from 'ng-zorro-antd/switch';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import type { DataField } from '@cube/api-core';
import { inferWidgetType, WidgetType } from '@cube/field-mapping';

interface SelectOption {
  value: string;
  label: string;
}

@Component({
  selector: 'app-field-input',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    NzInputModule, NzInputNumberModule, NzSelectModule,
    NzSwitchModule, NzDatePickerModule,
  ],
  template: `
    @switch (widgetType) {
      @case (WidgetType.Switch) {
        <nz-switch [ngModel]="!!value" (ngModelChange)="valueChange.emit($event)"></nz-switch>
      }
      @case (WidgetType.Select) {
        <nz-select [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" nzAllowClear style="width: 100%">
          @for (opt of options; track opt.value) {
            <nz-option [nzValue]="opt.value" [nzLabel]="opt.label"></nz-option>
          }
        </nz-select>
      }
      @case (WidgetType.TagList) {
        <nz-select [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" nzAllowClear style="width: 100%">
          @for (opt of options; track opt.value) {
            <nz-option [nzValue]="opt.value" [nzLabel]="opt.label"></nz-option>
          }
        </nz-select>
      }
      @case (WidgetType.Number) {
        <nz-input-number [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请输入' + (field.displayName || field.name)" style="width: 100%"></nz-input-number>
      }
      @case (WidgetType.Decimal) {
        <nz-input-number [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPrecision]="field.precision || 2"
          [nzPlaceHolder]="'请输入' + (field.displayName || field.name)" style="width: 100%"></nz-input-number>
      }
      @case (WidgetType.DateTime) {
        <nz-date-picker [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          nzShowTime [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" style="width: 100%"></nz-date-picker>
      }
      @case (WidgetType.Date) {
        <nz-date-picker [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" style="width: 100%"></nz-date-picker>
      }
      @case (WidgetType.TextArea) {
        <textarea nz-input [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" [nzAutosize]="{ minRows: 3 }"></textarea>
      }
      @case (WidgetType.RichText) {
        <textarea nz-input [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" [nzAutosize]="{ minRows: 3 }"></textarea>
      }
      @case (WidgetType.Password) {
        <input nz-input type="password" [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" />
      }
      @case (WidgetType.ReadOnly) {
        <span>{{ value ?? '-' }}</span>
      }
      @default {
        <input nz-input [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" />
      }
    }
  `,
})
export class FieldInputComponent {
  @Input() field!: DataField;
  @Input() value: any;
  @Output() valueChange = new EventEmitter<any>();

  WidgetType = WidgetType;

  get widgetType(): WidgetType {
    return inferWidgetType(this.field);
  }

  get options(): SelectOption[] {
    if (!this.field.dataSource) return [];
    try {
      const map = JSON.parse(this.field.dataSource) as Record<string, string>;
      return Object.entries(map).map(([value, label]) => ({ value, label }));
    } catch {
      return [];
    }
  }
}
