// NewLife.Cube.TDesign/web/src/components/FieldInput.vue
<template>
  <t-switch v-if="wt === WidgetType.Switch" :value="!!modelValue" @change="(v: boolean) => emit('update:modelValue', v)" />
  <t-select v-else-if="wt === WidgetType.Select || wt === WidgetType.TagList"
    :value="modelValue" @change="(v: any) => emit('update:modelValue', v)"
    :placeholder="'请选择' + (field.displayName || field.name)" clearable style="width: 100%">
    <t-option v-for="opt in options" :key="opt.value" :value="opt.value" :label="opt.label" />
  </t-select>
  <t-input-number v-else-if="wt === WidgetType.Number"
    :value="modelValue" @change="(v: number) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" theme="normal" style="width: 100%" />
  <t-input-number v-else-if="wt === WidgetType.Decimal"
    :value="modelValue" @change="(v: number) => emit('update:modelValue', v)"
    :decimal-places="field.precision || 2"
    :placeholder="'请输入' + (field.displayName || field.name)" theme="normal" style="width: 100%" />
  <t-date-picker v-else-if="wt === WidgetType.DateTime"
    :value="modelValue" @change="(v: any) => emit('update:modelValue', v)"
    enable-time-picker :placeholder="'请选择' + (field.displayName || field.name)" style="width: 100%" />
  <t-date-picker v-else-if="wt === WidgetType.Date"
    :value="modelValue" @change="(v: any) => emit('update:modelValue', v)"
    :placeholder="'请选择' + (field.displayName || field.name)" style="width: 100%" />
  <t-textarea v-else-if="wt === WidgetType.TextArea || wt === WidgetType.RichText"
    :value="modelValue" @change="(v: string) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" :autosize="{ minRows: 3 }" />
  <t-input v-else-if="wt === WidgetType.Password" type="password"
    :value="modelValue" @change="(v: string) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" />
  <span v-else-if="wt === WidgetType.ReadOnly" style="color: var(--td-text-color-secondary)">{{ modelValue ?? '-' }}</span>
  <t-input v-else
    :value="modelValue" @change="(v: string) => emit('update:modelValue', v)"
    :placeholder="'请输入' + (field.displayName || field.name)" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { DataField } from '@cube/api-core';
import { inferWidgetType, WidgetType } from '@cube/field-mapping';

const props = defineProps<{ field: DataField; modelValue: any }>();
const emit = defineEmits<{ 'update:modelValue': [v: any] }>();

const wt = computed(() => inferWidgetType(props.field));

const options = computed(() => {
  if (!props.field.dataSource) return [];
  try {
    const map = JSON.parse(props.field.dataSource) as Record<string, string>;
    return Object.entries(map).map(([value, label]) => ({ value, label }));
  } catch {
    return [];
  }
});
</script>

// NewLife.Cube.Angular/web/src/app/components/field-input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzInputNumberModule } from 'ng-zorro-antd/input-number';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzSwitchModule } from 'ng-zorro-antd/switch';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import type { DataField } from '@cube/api-core';
import { inferWidgetType, WidgetType } from '@cube/field-mapping';

interface SelectOption {
  value: string;
  label: string;
}

@Component({
  selector: 'app-field-input',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    NzInputModule, NzInputNumberModule, NzSelectModule,
    NzSwitchModule, NzDatePickerModule,
  ],
  template: `
    @switch (widgetType) {
      @case (WidgetType.Switch) {
        <nz-switch [ngModel]="!!value" (ngModelChange)="valueChange.emit($event)"></nz-switch>
      }
      @case (WidgetType.Select) {
        <nz-select [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" nzAllowClear style="width: 100%">
          @for (opt of options; track opt.value) {
            <nz-option [nzValue]="opt.value" [nzLabel]="opt.label"></nz-option>
          }
        </nz-select>
      }
      @case (WidgetType.TagList) {
        <nz-select [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" nzAllowClear style="width: 100%">
          @for (opt of options; track opt.value) {
            <nz-option [nzValue]="opt.value" [nzLabel]="opt.label"></nz-option>
          }
        </nz-select>
      }
      @case (WidgetType.Number) {
        <nz-input-number [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请输入' + (field.displayName || field.name)" style="width: 100%"></nz-input-number>
      }
      @case (WidgetType.Decimal) {
        <nz-input-number [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPrecision]="field.precision || 2"
          [nzPlaceHolder]="'请输入' + (field.displayName || field.name)" style="width: 100%"></nz-input-number>
      }
      @case (WidgetType.DateTime) {
        <nz-date-picker [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          nzShowTime [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" style="width: 100%"></nz-date-picker>
      }
      @case (WidgetType.Date) {
        <nz-date-picker [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [nzPlaceHolder]="'请选择' + (field.displayName || field.name)" style="width: 100%"></nz-date-picker>
      }
      @case (WidgetType.TextArea) {
        <textarea nz-input [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" [nzAutosize]="{ minRows: 3 }"></textarea>
      }
      @case (WidgetType.RichText) {
        <textarea nz-input [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" [nzAutosize]="{ minRows: 3 }"></textarea>
      }
      @case (WidgetType.Password) {
        <input nz-input type="password" [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" />
      }
      @case (WidgetType.ReadOnly) {
        <span>{{ value ?? '-' }}</span>
      }
      @default {
        <input nz-input [ngModel]="value" (ngModelChange)="valueChange.emit($event)"
          [placeholder]="'请输入' + (field.displayName || field.name)" />
      }
    }
  `,
})
export class FieldInputComponent {
  @Input() field!: DataField;
  @Input() value: any;
  @Output() valueChange = new EventEmitter<any>();

  WidgetType = WidgetType;

  get widgetType(): WidgetType {
    return inferWidgetType(this.field);
  }

  get options(): SelectOption[] {
    if (!this.field.dataSource) return [];
    try {
      const map = JSON.parse(this.field.dataSource) as Record<string, string>;
      return Object.entries(map).map(([value, label]) => ({ value, label }));
    } catch {
      return [];
    }
  }
}
