// NewLife.Cube.React/web/src/pages/ProfileSecurity/index.tsx
/**
 * 安全中心（对齐 Vue 皮肤 pages/ProfileSecurity.vue + MFA 增强）
 *
 * 1. 邮箱/手机验证状态（/Auth/Info 的 mailVerified/mobileVerified）
 * 2. 验证/更换联系方式（发码 /Auth/SendCode action=bind，提交 /Auth/VerifyContact）
 * 3. MFA 双因素认证：状态/绑定（二维码+密钥）/激活（备用码）/解绑
 */
import { useEffect, useState } from 'react';
import { Alert, Button, Card, Descriptions, Form, Input, Modal, Space, Tag, message } from 'antd';
import { api } from '@/api';
import { useUserStore } from '@/stores/user';

type Panel = 'mail' | 'sms' | null;

export default function ProfileSecurityPage() {
  const [form] = Form.useForm();
  const userInfo = useUserStore((s) => s.userInfo);
  const [panel, setPanel] = useState<Panel>(null);
  const [sending, setSending] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // MFA 状态
  const [mfaEnabled, setMfaEnabled] = useState(false);
  const [mfaAvailable, setMfaAvailable] = useState(false);
  const [mfaSetup, setMfaSetup] = useState<{ qrCodeUri: string; secret: string } | null>(null);
  const [backupCodes, setBackupCodes] = useState<string[] | null>(null);
  const [mfaCode, setMfaCode] = useState('');
  const [mfaBusy, setMfaBusy] = useState(false);
  const [disableOpen, setDisableOpen] = useState(false);
  const [disableCode, setDisableCode] = useState('');

  useEffect(() => {
    api.user
      .mfaStatus()
      .then((res) => {
        setMfaEnabled(!!res.data?.enabled);
        setMfaAvailable(!!res.data?.available);
      })
      .catch(() => {
        // 后端不支持 MFA 时静默
      });
  }, []);

  const handleSendVerifyCode = async () => {
    const values = await form.validateFields(['account']);
    setSending(true);
    try {
      await api.user.sendCode({
        channel: panel === 'mail' ? 'Mail' : 'Sms',
        username: values.account,
        action: 'bind',
      });
      message.success('验证码已发送');
    } catch (err) {
      message.error((err as Error)?.message || '发送失败');
    } finally {
      setSending(false);
    }
  };

  const handleVerify = async () => {
    const values = await form.validateFields();
    setSubmitting(true);
    try {
      const res = await api.user.verifyContact({
        channel: panel === 'mail' ? 'Mail' : 'Sms',
        account: values.account,
        code: values.code,
      });
      message.success('验证成功');
      setPanel(null);
      form.resetFields();
      // 刷新用户信息
      void useUserStore.getState().fetchUserInfo();
    } catch (err) {
      message.error((err as Error)?.message || '验证失败');
    } finally {
      setSubmitting(false);
    }
  };

  // ── MFA ─────────────────────────────────────────────
  const handleMfaSetup = async () => {
    setMfaBusy(true);
    try {
      const res = await api.user.mfaSetup();
      setMfaSetup(res.data);
    } catch (err) {
      message.error((err as Error)?.message || '初始化失败');
    } finally {
      setMfaBusy(false);
    }
  };

  const handleMfaActivate = async () => {
    if (!mfaCode) return;
    setMfaBusy(true);
    try {
      const res = await api.user.mfaActivate(mfaCode);
      setBackupCodes(res.data?.backupCodes ?? []);
      setMfaEnabled(true);
      setMfaSetup(null);
      message.success('MFA 已开启');
    } catch (err) {
      message.error((err as Error)?.message || '激活失败');
    } finally {
      setMfaBusy(false);
    }
  };

  const handleMfaDisable = async () => {
    if (!disableCode) return;
    setMfaBusy(true);
    try {
      await api.user.mfaDisable(disableCode);
      setMfaEnabled(false);
      setDisableOpen(false);
      setDisableCode('');
      message.success('MFA 已关闭');
    } catch (err) {
      message.error((err as Error)?.message || '关闭失败');
    } finally {
      setMfaBusy(false);
    }
  };

  return (
    <div style={{ maxWidth: 720, margin: '0 auto' }}>
      <Card title="联系方式验证" style={{ marginBottom: 16 }}>
        <Descriptions column={1} size="middle">
          <Descriptions.Item label="邮箱">
            <Space>
              <span>{userInfo?.mail || '未绑定'}</span>
              {userInfo?.mail && (
                <Tag color={userInfo.mailVerified ? 'success' : 'warning'}>
                  {userInfo.mailVerified ? '已验证' : '未验证'}
                </Tag>
              )}
              {userInfo?.mail && (
                <Button size="small" onClick={() => setPanel(panel === 'mail' ? null : 'mail')}>
                  {userInfo.mailVerified ? '更换' : '验证'}
                </Button>
              )}
            </Space>
          </Descriptions.Item>
          <Descriptions.Item label="手机号">
            <Space>
              <span>{userInfo?.mobile || '未绑定'}</span>
              {userInfo?.mobile && (
                <Tag color={userInfo.mobileVerified ? 'success' : 'warning'}>
                  {userInfo.mobileVerified ? '已验证' : '未验证'}
                </Tag>
              )}
              {userInfo?.mobile && (
                <Button size="small" onClick={() => setPanel(panel === 'sms' ? null : 'sms')}>
                  {userInfo.mobileVerified ? '更换' : '验证'}
                </Button>
              )}
            </Space>
          </Descriptions.Item>
        </Descriptions>

        {panel && (
          <Form form={form} layout="vertical" style={{ marginTop: 16 }}>
            <Form.Item
              name="account"
              label={panel === 'mail' ? '新邮箱' : '新手机号'}
              rules={[
                { required: true, message: '请输入' },
                panel === 'mail'
                  ? { type: 'email', message: '邮箱格式不正确' }
                  : { pattern: /^1\d{10}$/, message: '手机号格式不正确' },
              ]}
            >
              <Input placeholder={panel === 'mail' ? '请输入新邮箱' : '请输入新手机号'} />
            </Form.Item>
            <Form.Item name="code" label="验证码" rules={[{ required: true, message: '请输入验证码' }]}>
              <Space.Compact style={{ width: '100%' }}>
                <Input placeholder="验证码" maxLength={6} />
                <Button loading={sending} onClick={() => void handleSendVerifyCode()}>
                  发送验证码
                </Button>
              </Space.Compact>
            </Form.Item>
            <Button type="primary" loading={submitting} onClick={() => void handleVerify()}>
              验证
            </Button>
          </Form>
        )}
      </Card>

      <Card title="双重验证（MFA）">
        {!mfaAvailable ? (
          <Alert type="info" showIcon message="当前系统未开放 MFA 功能" />
        ) : (
          <Space direction="vertical" style={{ width: '100%' }}>
            {mfaEnabled ? (
              <Alert
                type="success"
                showIcon
                message="MFA 已开启"
                description="登录时需要输入身份验证器动态验证码。"
                action={<Button danger size="small" onClick={() => setDisableOpen(true)}>关闭 MFA</Button>}
              />
            ) : (
              <Alert
                type="warning"
                showIcon
                message="MFA 未开启"
                description="开启后登录将需要身份验证器动态验证码，提升账号安全性。"
                action={
                  <Button type="primary" size="small" loading={mfaBusy} onClick={() => void handleMfaSetup()}>
                    开启 MFA
                  </Button>
                }
              />
            )}

            {mfaSetup && (
              <Card size="small" title="绑定 MFA">
                <Space direction="vertical" style={{ width: '100%' }}>
                  <img
                    src={mfaSetup.qrCodeUri}
                    alt="MFA 二维码"
                    style={{ width: 160, height: 160, alignSelf: 'center' }}
                  />
                  <Alert
                    type="info"
                    showIcon
                    message="使用身份验证器 App 扫码，或手动输入密钥"
                    description={mfaSetup.secret}
                  />
                  <Space.Compact style={{ width: '100%' }}>
                    <Input
                      placeholder="输入 App 中显示的 6 位验证码"
                      maxLength={6}
                      value={mfaCode}
                      onChange={(e) => setMfaCode(e.target.value)}
                    />
                    <Button type="primary" loading={mfaBusy} onClick={() => void handleMfaActivate()}>
                      激活
                    </Button>
                  </Space.Compact>
                </Space>
              </Card>
            )}

            {backupCodes && (
              <Alert
                type="warning"
                showIcon
                message="请妥善保存备用验证码"
                description={
                  <div>
                    每个备用码仅可使用一次，用于无法使用验证器时恢复登录：
                    <pre style={{ background: '#f5f5f5', padding: 8, borderRadius: 4 }}>{backupCodes.join('\n')}</pre>
                  </div>
                }
                action={<Button size="small" onClick={() => setBackupCodes(null)}>我已保存</Button>}
              />
            )}
          </Space>
        )}
      </Card>

      <Modal
        title="关闭 MFA"
        open={disableOpen}
        onCancel={() => setDisableOpen(false)}
        onOk={() => void handleMfaDisable()}
        confirmLoading={mfaBusy}
        okText="关闭"
        okButtonProps={{ danger: true }}
      >
        <p>请输入当前身份验证器中的 6 位动态验证码以确认关闭：</p>
        <Input
          placeholder="6 位动态验证码"
          maxLength={6}
          value={disableCode}
          onChange={(e) => setDisableCode(e.target.value)}
        />
      </Modal>
    </div>
  );
}

// NewLife.Cube.Vue/web/core/pages/ProfileSecurity.vue
<!--
  安全中心 — 邮箱/手机验证状态与验证/更换入口

  展示当前用户邮箱/手机验证状态（/Auth/Info 的 mailVerified/mobileVerified），
  支持已验证用户验证/更换联系方式（发码走 /Auth/SendCode action=bind，提交走 /Auth/VerifyContact）。
-->
<template>
  <div class="security-page">
    <h2 class="page-title">安全中心</h2>

    <!-- 邮箱 -->
    <el-card class="contact-card" shadow="never">
      <div class="contact-row">
        <div class="contact-info">
          <div class="contact-label">邮箱</div>
          <div class="contact-value">
            <span class="contact-text">{{ info?.mail || '未绑定' }}</span>
            <el-tag :type="info?.mailVerified ? 'success' : 'warning'" size="small">
              {{ info?.mailVerified ? '已验证' : '未验证' }}
            </el-tag>
          </div>
        </div>
        <el-button
          v-if="info?.mail"
          type="primary"
          plain
          size="small"
          @click="openPanel('mail')"
        >
          {{ info?.mailVerified ? '更换' : '验证' }}
        </el-button>
      </div>
    </el-card>

    <!-- 手机 -->
    <el-card class="contact-card" shadow="never">
      <div class="contact-row">
        <div class="contact-info">
          <div class="contact-label">手机号</div>
          <div class="contact-value">
            <span class="contact-text">{{ info?.mobile || '未绑定' }}</span>
            <el-tag :type="info?.mobileVerified ? 'success' : 'warning'" size="small">
              {{ info?.mobileVerified ? '已验证' : '未验证' }}
            </el-tag>
          </div>
        </div>
        <el-button
          v-if="info?.mobile"
          type="primary"
          plain
          size="small"
          @click="openPanel('sms')"
        >
          {{ info?.mobileVerified ? '更换' : '验证' }}
        </el-button>
      </div>
    </el-card>

    <!-- 验证/更换面板 -->
    <el-card v-if="panel" class="verify-panel" shadow="never">
      <template #header>
        <span>
          {{ panel === 'mail' ? '验证/更换邮箱' : '验证/更换手机号' }}
          <el-button text type="primary" size="small" @click="panel = null">收起</el-button>
        </span>
      </template>
      <el-form label-width="90px" @submit.prevent>
        <el-form-item label="新邮箱/手机" required>
          <el-input
            v-model="verifyForm.account"
            :placeholder="panel === 'mail' ? '请输入新邮箱' : '请输入新手机号'"
            data-cy="verify-account"
          />
        </el-form-item>
        <el-form-item label="验证码" required>
          <div class="code-row">
            <el-input
              v-model="verifyForm.code"
              placeholder="请输入验证码"
              maxlength="6"
              data-cy="verify-code"
              @keyup.enter="handleVerify"
            />
            <el-button :disabled="sending" @click="handleSendVerifyCode">
              {{ sending ? '发送中...' : '发送验证码' }}
            </el-button>
          </div>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" :loading="submitting" @click="handleVerify" data-cy="verify-submit">
            提交验证
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <p class="security-tip">
      已验证的邮箱/手机可用于接收系统通知与安全提醒。依据《中华人民共和国个人信息保护法》，请妥善保管您的联系方式。
    </p>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { ElMessage } from 'element-plus';
import request from '../utils/request';
import { sendCode, verifyContact } from '../utils/loginApi';

interface SecurityInfo {
  mail?: string;
  mobile?: string;
  mailVerified?: boolean;
  mobileVerified?: boolean;
}

/** 当前用户信息 */
const info = ref<SecurityInfo | null>(null);
/** 展开的验证面板：mail / sms / null */
const panel = ref<'mail' | 'sms' | null>(null);
/** 提交中 */
const submitting = ref(false);
/** 发码中 */
const sending = ref(false);

const verifyForm = reactive<{ account: string; code: string }>({ account: '', code: '' });

function isMobile(v: string): boolean {
  return /^1[3-9]\d{9}$/.test(v);
}

function isMail(v: string): boolean {
  return /^[\w.+-]+@[\w-]+(\.[\w-]+)+$/.test(v);
}

/** 拉取当前用户信息（含验证状态） */
async function fetchInfo(): Promise<void> {
  try {
    const res = (await request.get('/Auth/Info')) as unknown as {
      code?: number;
      data?: SecurityInfo;
    };
    if (res?.code === 0 && res.data) {
      info.value = res.data;
    }
  } catch (err: unknown) {
    console.error('获取用户信息失败:', err);
  }
}

/** 展开验证面板 */
function openPanel(channel: 'mail' | 'sms'): void {
  panel.value = channel;
  verifyForm.account = '';
  verifyForm.code = '';
}

/** 发送验证码（action=bind） */
async function handleSendVerifyCode(): Promise<void> {
  const account = verifyForm.account.trim();
  if (!account) {
    ElMessage.warning(panel.value === 'mail' ? '请输入邮箱' : '请输入手机号');
    return;
  }
  if (panel.value === 'mail' && !isMail(account)) {
    ElMessage.warning('邮箱格式不正确');
    return;
  }
  if (panel.value === 'sms' && !isMobile(account)) {
    ElMessage.warning('手机号格式不正确');
    return;
  }

  sending.value = true;
  try {
    const res = await sendCode(panel.value === 'mail' ? 'Mail' : 'Sms', account, 'bind');
    if (res.code === 0) {
      ElMessage.success('验证码已发送，请查收');
    } else {
      ElMessage.error(res.message || '验证码发送失败');
    }
  } catch (err: unknown) {
    ElMessage.error(err instanceof Error ? err.message : '验证码发送失败');
  } finally {
    sending.value = false;
  }
}

/** 提交验证/更换 */
async function handleVerify(): Promise<void> {
  if (!panel.value) return;
  const account = verifyForm.account.trim();
  if (!account) {
    ElMessage.warning(panel.value === 'mail' ? '请输入邮箱' : '请输入手机号');
    return;
  }
  if (!verifyForm.code.trim()) {
    ElMessage.warning('请输入验证码');
    return;
  }

  submitting.value = true;
  try {
    const res = await verifyContact(panel.value, account, verifyForm.code.trim());
    if (res.code === 0 && res.data) {
      ElMessage.success('验证成功');
      panel.value = null;
      // 刷新验证状态
      await fetchInfo();
    } else {
      ElMessage.error(res.message || '验证失败');
    }
  } catch (err: unknown) {
    ElMessage.error(err instanceof Error ? err.message : '验证失败，请稍后重试');
  } finally {
    submitting.value = false;
  }
}

onMounted(() => {
  fetchInfo();
});
</script>

<style scoped>
.security-page {
  max-width: 720px;
  margin: 0 auto;
  padding: 24px 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.page-title {
  margin: 0 0 8px;
  font-size: 22px;
  font-weight: 600;
  color: var(--el-text-color-primary);
}

.contact-card {
  border-radius: 12px;
}

.contact-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}

.contact-info {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.contact-label {
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

.contact-value {
  display: flex;
  align-items: center;
  gap: 10px;
}

.contact-text {
  font-size: 15px;
  color: var(--el-text-color-primary);
  word-break: break-all;
}

.verify-panel {
  border-radius: 12px;
}

.code-row {
  display: flex;
  gap: 8px;
  width: 100%;
}

.code-row .el-input {
  flex: 1;
}

.security-tip {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  line-height: 1.7;
  margin: 0;
}
</style>
