// NewLife.Cube.Vuetify/web/src/views/dynamic/DynamicPage.vue
<template>
  <div>
    <!-- ECharts 图表区域 -->
    <v-card v-if="chartList.length" class="mb-4 pa-4">
      <div
        v-for="(_, idx) in chartList"
        :key="idx"
        :ref="(el: any) => setChartRef(el as HTMLElement, idx)"
        style="width: 100%; height: 400px"
      />
    </v-card>

    <!-- 搜索 -->
    <v-card v-if="searchFields.length" class="mb-4 pa-4">
      <v-form @submit.prevent="handleSearch">
        <v-row dense>
          <v-col v-for="field in searchFields" :key="field.name" cols="12" sm="6" md="3">
            <FieldInput :field="field" :value="searchForm[field.name]" @update:value="(v: any) => (searchForm[field.name] = v)" />
          </v-col>
          <v-col cols="12" sm="6" md="3" class="d-flex align-center ga-2">
            <v-btn type="submit" color="primary" prepend-icon="mdi-magnify">搜索</v-btn>
            <v-btn variant="outlined" @click="handleReset">重置</v-btn>
          </v-col>
        </v-row>
      </v-form>
    </v-card>

    <!-- 操作栏 -->
    <div class="d-flex justify-space-between mb-3">
      <div class="d-flex ga-2">
        <v-btn v-if="canAdd" color="primary" prepend-icon="mdi-plus" @click="handleAdd">新增</v-btn>
        <v-btn v-if="canDelete" color="error" :disabled="!selected.length" prepend-icon="mdi-delete" @click="handleBatchDelete">批量删除</v-btn>
      </div>
      <div class="d-flex ga-2">
        <v-menu v-if="canExport">
          <template #activator="{ props: menuProps }">
            <v-btn variant="outlined" v-bind="menuProps" append-icon="mdi-chevron-down">导出</v-btn>
          </template>
          <v-list density="compact">
            <v-list-item v-for="opt in exportOptions" :key="opt.value" @click="handleExport(opt.value)">
              <v-list-item-title>{{ opt.label }}</v-list-item-title>
            </v-list-item>
          </v-list>
        </v-menu>
        <v-btn v-if="canImport" variant="outlined" @click="triggerImport">导入</v-btn>
        <input ref="fileInput" type="file" style="display: none;" @change="handleImport" />
      </div>
    </div>

    <!-- 数据表格 -->
    <v-data-table
      :headers="headers"
      :items="tableData"
      :loading="loading"
      show-select
      v-model="selected"
      item-value="id"
      :items-per-page="pageSize"
      hide-default-footer
    >
      <template #item.actions="{ item }">
        <v-btn variant="text" size="small" @click="handleDetail(item)">详情</v-btn>
        <v-btn v-if="canEdit" variant="text" size="small" @click="handleEdit(item)">编辑</v-btn>
        <v-btn v-if="canDelete" variant="text" size="small" color="error" @click="confirmDelete(item)">删除</v-btn>
      </template>
      <template #bottom>
        <!-- 统计行 -->
        <div v-if="statData" class="d-flex ga-4 pa-2" style="background: #f5f5f5;">
          <span class="font-weight-bold">合计</span>
          <span v-for="f in listFields.filter(f => statData![f.name] != null)" :key="f.name">
            {{ f.displayName || f.name }}：{{ statData[f.name] }}
          </span>
        </div>
        <div class="d-flex justify-end align-center pa-2 ga-4">
          <span class="text-body-2">共 {{ total }} 条</span>
          <v-pagination v-model="page" :length="totalPages" density="compact" :total-visible="5" @update:model-value="loadData" />
        </div>
      </template>
    </v-data-table>

    <!-- 新增/编辑弹窗 -->
    <v-dialog v-model="formDialogVisible" max-width="640" persistent>
      <v-card>
        <v-card-title>{{ isEdit ? '编辑' : '新增' }}</v-card-title>
        <v-card-text>
          <v-form>
            <v-row dense>
              <v-col v-for="field in formFields" :key="field.name" cols="12">
                <FieldInput :field="field" :value="formData[field.name]" @update:value="(v: any) => (formData[field.name] = v)" />
              </v-col>
            </v-row>
          </v-form>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="formDialogVisible = false">取消</v-btn>
          <v-btn color="primary" :loading="submitLoading" @click="handleFormSubmit">确定</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- 详情弹窗 -->
    <v-dialog v-model="detailDialogVisible" max-width="640">
      <v-card>
        <v-card-title>详情</v-card-title>
        <v-card-text>
          <v-table density="compact">
            <tbody>
              <tr v-for="field in detailFields" :key="field.name">
                <td class="font-weight-bold" style="width: 160px;">{{ field.displayName || field.name }}</td>
                <td>{{ detailData[field.name] ?? '-' }}</td>
              </tr>
            </tbody>
          </v-table>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="detailDialogVisible = false">关闭</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- 删除确认 -->
    <v-dialog v-model="deleteDialogVisible" max-width="360">
      <v-card>
        <v-card-title>确认删除</v-card-title>
        <v-card-text>确定要删除此记录吗？</v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn variant="text" @click="deleteDialogVisible = false">取消</v-btn>
          <v-btn color="error" @click="doDelete">删除</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch, onMounted, onBeforeUnmount, nextTick, markRaw } from 'vue';
import { useRoute } from 'vue-router';
import { FieldKind, Auth, type DataField } from '@cube/api-core';
import * as echarts from 'echarts';
import cubeApi from '@/api';
import { useUserStore } from '@/stores/user';
import FieldInput from '@/components/FieldInput.vue';

const route = useRoute();
const userStore = useUserStore();
const typePath = computed(() => '/' + (route.params.type as string[] || []).join('/'));

// --- 权限控制 ---
const menuPerms = computed(() => userStore.getMenuPermission(typePath.value));
const canAdd = computed(() => String(Auth.ADD) in menuPerms.value);
const canEdit = computed(() => String(Auth.EDIT) in menuPerms.value);
const canDelete = computed(() => String(Auth.DELETE) in menuPerms.value);
const canExport = computed(() => String(Auth.EXPORT) in menuPerms.value);
const canImport = computed(() => String(Auth.IMPORT) in menuPerms.value);

const exportOptions = [
  { label: '导出 Excel', value: 'Excel' },
  { label: '导出 CSV', value: 'Csv' },
  { label: '导出 JSON', value: 'Json' },
  { label: '导出 XML', value: 'Xml' },
  { label: '导出模板', value: 'ExcelTemplate' },
];

// 字段
const listFields = ref<DataField[]>([]);
const searchFields = ref<DataField[]>([]);
const addFields = ref<DataField[]>([]);
const editFields = ref<DataField[]>([]);
const detailFields = ref<DataField[]>([]);

// 表格
const tableData = ref<Record<string, any>[]>([]);
const loading = ref(false);
const selected = ref<any[]>([]);
const page = ref(1);
const pageSize = ref(20);
const total = ref(0);
const totalPages = computed(() => Math.ceil(total.value / pageSize.value) || 1);
const statData = ref<Record<string, unknown> | null>(null);

// 搜索
const searchForm = reactive<Record<string, any>>({});

// 表单弹窗
const formDialogVisible = ref(false);
const isEdit = ref(false);
const formData = reactive<Record<string, any>>({});
const submitLoading = ref(false);

// 详情弹窗
const detailDialogVisible = ref(false);
const detailData = reactive<Record<string, any>>({});

// 删除确认
const deleteDialogVisible = ref(false);
const deleteTarget = ref<Record<string, any> | null>(null);

// 文件导入
const fileInput = ref<HTMLInputElement | null>(null);

// ECharts
const chartList = ref<any[]>([]);
const chartInstances = ref<any[]>([]);

// 表头
const headers = computed(() => {
  const cols = listFields.value
    .filter((f) => f.visible !== false)
    .map((f) => ({
      title: f.displayName || f.name,
      key: f.name,
      sortable: false,
    }));
  cols.push({ title: '操作', key: 'actions', sortable: false });
  return cols;
});

const formFields = computed(() => (isEdit.value ? editFields.value : addFields.value));

async function loadFields() {
  const path = typePath.value;
  const [list, search, add, edit, detail] = await Promise.all([
    cubeApi.page.getFields(path, FieldKind.List),
    cubeApi.page.getFields(path, FieldKind.Search),
    cubeApi.page.getFields(path, FieldKind.Add),
    cubeApi.page.getFields(path, FieldKind.Edit),
    cubeApi.page.getFields(path, FieldKind.Detail),
  ]);
  listFields.value = list.data || [];
  searchFields.value = search.data || [];
  addFields.value = add.data || [];
  editFields.value = edit.data || [];
  detailFields.value = detail.data || [];
}

async function loadData() {
  loading.value = true;
  try {
    const res = await cubeApi.page.getList(typePath.value, {
      pageIndex: page.value - 1,
      pageSize: pageSize.value,
      ...searchForm,
    });
    tableData.value = res.data || [];
    statData.value = (res.stat as Record<string, unknown>) ?? null;
    if (res.page) total.value = res.page.totalCount || 0;
  } finally {
    loading.value = false;
  }
}

async function loadChartData() {
  try {
    const res = await cubeApi.page.getChartData(typePath.value);
    chartList.value = Array.isArray(res.data) && res.data.length > 0 ? res.data : [];
  } catch {
    chartList.value = [];
  }
}

function setChartRef(el: HTMLElement | null, idx: number) {
  if (!el) return;
  nextTick(() => {
    if (chartInstances.value[idx]) chartInstances.value[idx].dispose();
    const instance = markRaw(echarts.init(el));
    if (chartList.value[idx]) instance.setOption(chartList.value[idx]);
    chartInstances.value[idx] = instance;
  });
}

function onChartResize() {
  for (const inst of chartInstances.value) { inst?.resize(); }
}

function handleSearch() { page.value = 1; loadData(); }
function handleReset() { Object.keys(searchForm).forEach((k) => delete searchForm[k]); page.value = 1; loadData(); }

function handleAdd() { isEdit.value = false; Object.keys(formData).forEach((k) => delete formData[k]); formDialogVisible.value = true; }
function handleEdit(row: Record<string, any>) { isEdit.value = true; Object.keys(formData).forEach((k) => delete formData[k]); Object.assign(formData, row); formDialogVisible.value = true; }

async function handleFormSubmit() {
  submitLoading.value = true;
  try {
    if (isEdit.value) await cubeApi.page.update(typePath.value, formData);
    else await cubeApi.page.add(typePath.value, formData);
    formDialogVisible.value = false;
    loadData();
  } finally { submitLoading.value = false; }
}

function handleDetail(row: Record<string, any>) { Object.keys(detailData).forEach((k) => delete detailData[k]); Object.assign(detailData, row); detailDialogVisible.value = true; }
function confirmDelete(row: Record<string, any>) { deleteTarget.value = row; deleteDialogVisible.value = true; }
async function doDelete() { if (deleteTarget.value) { await cubeApi.page.remove(typePath.value, deleteTarget.value.id); deleteDialogVisible.value = false; deleteTarget.value = null; loadData(); } }
async function handleBatchDelete() { if (!selected.value.length) return; await cubeApi.page.deleteSelect(typePath.value, selected.value as number[]); selected.value = []; loadData(); }
function handleExport(format: string) { window.open(cubeApi.page.getExportUrl(typePath.value, format), '_blank'); }
function triggerImport() { fileInput.value?.click(); }

async function handleImport(e: Event) {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;
  await cubeApi.page.importFile(typePath.value, file);
  input.value = '';
  loadData();
}

watch(typePath, () => { page.value = 1; loadFields().then(loadData); loadChartData(); });
onMounted(() => { loadFields().then(loadData); loadChartData(); window.addEventListener('resize', onChartResize); });
onBeforeUnmount(() => { window.removeEventListener('resize', onChartResize); for (const inst of chartInstances.value) { inst?.dispose(); } });
</script>

// NewLife.Cube.Angular/web/src/app/pages/dynamic/dynamic-page.component.ts
import { Component, OnInit, OnDestroy, ElementRef, ViewChildren, QueryList, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { NzTableModule } from 'ng-zorro-antd/table';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzModalModule, NzModalService } from 'ng-zorro-antd/modal';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzDescriptionsModule } from 'ng-zorro-antd/descriptions';
import { NzPopconfirmModule } from 'ng-zorro-antd/popconfirm';
import { NzUploadModule } from 'ng-zorro-antd/upload';
import { NzSpaceModule } from 'ng-zorro-antd/space';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzDividerModule } from 'ng-zorro-antd/divider';
import { NzDropDownModule } from 'ng-zorro-antd/dropdown';
import { FieldKind, Auth, type DataField } from '@cube/api-core';
import { ApiService } from '../../services/api.service';
import { UserService } from '../../services/user.service';
import { FieldInputComponent } from '../../components/field-input.component';
import * as echarts from 'echarts';

@Component({
  selector: 'app-dynamic-page',
  standalone: true,
  imports: [
    CommonModule, FormsModule,
    NzTableModule, NzButtonModule, NzCardModule, NzFormModule,
    NzModalModule, NzDescriptionsModule, NzPopconfirmModule,
    NzUploadModule, NzSpaceModule, NzIconModule, NzDividerModule,
    NzDropDownModule, FieldInputComponent,
  ],
  template: `
    <!-- ECharts 图表 -->
    @if (chartList.length) {
      <nz-card style="margin-bottom: 16px;">
        @for (opt of chartList; track $index) {
          <div #chartContainer style="width: 100%; height: 400px;"></div>
        }
      </nz-card>
    }

    <!-- 搜索 -->
    @if (searchFields.length) {
      <nz-card style="margin-bottom: 16px;">
        <form nz-form nzLayout="inline" (ngSubmit)="handleSearch()">
          @for (field of searchFields; track field.name) {
            <nz-form-item>
              <nz-form-label>{{ field.displayName || field.name }}</nz-form-label>
              <nz-form-control>
                <app-field-input [field]="field" [value]="searchForm[field.name]"
                  (valueChange)="searchForm[field.name] = $event"></app-field-input>
              </nz-form-control>
            </nz-form-item>
          }
          <nz-form-item>
            <nz-space>
              <button *nzSpaceItem nz-button nzType="primary" type="submit">
                <span nz-icon nzType="search"></span>搜索
              </button>
              <button *nzSpaceItem nz-button (click)="handleReset()">重置</button>
            </nz-space>
          </nz-form-item>
        </form>
      </nz-card>
    }

    <!-- 操作栏 -->
    <div style="display: flex; justify-content: space-between; margin-bottom: 12px;">
      <nz-space>
        @if (canAdd) {
          <button *nzSpaceItem nz-button nzType="primary" (click)="handleAdd()">
            <span nz-icon nzType="plus"></span>新增
          </button>
        }
        @if (canDelete) {
          <button *nzSpaceItem nz-button nzDanger [disabled]="!checkedIds.size" (click)="handleBatchDelete()">
            <span nz-icon nzType="delete"></span>批量删除
          </button>
        }
      </nz-space>
      <nz-space>
        @if (canExport) {
          <button *nzSpaceItem nz-button nz-dropdown [nzDropdownMenu]="exportMenu">
            <span nz-icon nzType="download"></span>导出 <span nz-icon nzType="down"></span>
          </button>
          <nz-dropdown-menu #exportMenu="nzDropdownMenu">
            <ul nz-menu>
              @for (opt of exportOptions; track opt.value) {
                <li nz-menu-item (click)="handleExport(opt.value)">{{ opt.label }}</li>
              }
            </ul>
          </nz-dropdown-menu>
        }
        @if (canImport) {
          <nz-upload *nzSpaceItem [nzAction]="typePath + '/ImportFile'" [nzShowUploadList]="false" (nzChange)="onImportChange($event)">
            <button nz-button><span nz-icon nzType="upload"></span>导入</button>
          </nz-upload>
        }
      </nz-space>
    </div>

    <!-- 数据表格 -->
    <nz-table
      #basicTable
      [nzData]="tableData"
      [nzLoading]="loading"
      [nzPageIndex]="pageIndex"
      [nzPageSize]="pageSize"
      [nzTotal]="total"
      [nzFrontPagination]="false"
      nzShowSizeChanger
      (nzPageIndexChange)="onPageChange($event)"
      (nzPageSizeChange)="onPageSizeChange($event)"
    >
      <thead>
        <tr>
          <th nzShowCheckbox [(nzChecked)]="allChecked" (nzCheckedChange)="onAllChecked($event)"></th>
          @for (field of listFields; track field.name) {
            @if (field.visible !== false) {
              <th>{{ field.displayName || field.name }}</th>
            }
          }
          <th nzWidth="180px">操作</th>
        </tr>
      </thead>
      <tbody>
        @for (row of basicTable.data; track row['id']) {
          <tr>
            <td nzShowCheckbox [nzChecked]="checkedIds.has(row['id'])" (nzCheckedChange)="onItemChecked(row['id'], $event)"></td>
            @for (field of listFields; track field.name) {
              @if (field.visible !== false) {
                <td>{{ row[field.name] }}</td>
              }
            }
            <td>
              <a (click)="handleDetail(row)">详情</a>
              @if (canEdit) {
                <nz-divider nzType="vertical"></nz-divider>
                <a (click)="handleEdit(row)">编辑</a>
              }
              @if (canDelete) {
                <nz-divider nzType="vertical"></nz-divider>
                <a nz-popconfirm nzPopconfirmTitle="确认删除？" (nzOnConfirm)="handleDelete(row)" class="text-danger">删除</a>
              }
            </td>
          </tr>
        }
        <!-- 统计行 -->
        @if (statData) {
          <tr style="background: #fafafa; font-weight: bold;">
            <td></td>
            @for (field of listFields; track field.name; let idx = $index) {
              @if (field.visible !== false) {
                <td>{{ idx === 0 ? '合计' : (statData[field.name] != null ? statData[field.name] : '') }}</td>
              }
            }
            <td></td>
          </tr>
        }
      </tbody>
    </nz-table>

    <!-- 新增/编辑弹窗 -->
    <nz-modal [(nzVisible)]="formVisible" [nzTitle]="isEdit ? '编辑' : '新增'" nzWidth="640" (nzOnOk)="handleFormSubmit()" [nzOkLoading]="submitLoading">
      <ng-container *nzModalContent>
        <form nz-form nzLayout="vertical">
          @for (field of formFields; track field.name) {
            <nz-form-item>
              <nz-form-label [nzRequired]="!!field.required">{{ field.displayName || field.name }}</nz-form-label>
              <nz-form-control>
                <app-field-input [field]="field" [value]="formData[field.name]"
                  (valueChange)="formData[field.name] = $event"></app-field-input>
              </nz-form-control>
            </nz-form-item>
          }
        </form>
      </ng-container>
    </nz-modal>

    <!-- 详情弹窗 -->
    <nz-modal [(nzVisible)]="detailVisible" nzTitle="详情" nzWidth="640" [nzFooter]="null">
      <ng-container *nzModalContent>
        <nz-descriptions nzBordered [nzColumn]="1">
          @for (field of detailFields; track field.name) {
            <nz-descriptions-item [nzTitle]="field.displayName || field.name">
              {{ detailData[field.name] ?? '-' }}
            </nz-descriptions-item>
          }
        </nz-descriptions>
      </ng-container>
    </nz-modal>
  `,
  styles: [`.text-danger { color: #ff4d4f; }`],
})
export class DynamicPageComponent implements OnInit, OnDestroy, AfterViewChecked {
  @ViewChildren('chartContainer') chartContainers!: QueryList<ElementRef<HTMLDivElement>>;

  typePath = '';
  listFields: DataField[] = [];
  searchFields: DataField[] = [];
  addFields: DataField[] = [];
  editFields: DataField[] = [];
  detailFields: DataField[] = [];

  tableData: Record<string, any>[] = [];
  loading = false;
  pageIndex = 1;
  pageSize = 20;
  total = 0;
  statData: Record<string, any> | null = null;

  searchForm: Record<string, any> = {};
  checkedIds = new Set<number>();
  allChecked = false;

  formVisible = false;
  isEdit = false;
  formData: Record<string, any> = {};
  submitLoading = false;

  detailVisible = false;
  detailData: Record<string, any> = {};

  // 权限
  canAdd = false;
  canEdit = false;
  canDelete = false;
  canExport = false;
  canImport = false;

  // ECharts
  chartList: any[] = [];
  private chartInstances: any[] = [];
  private chartsInitialized = false;
  private resizeHandler = () => { for (const inst of this.chartInstances) { inst?.resize(); } };

  exportOptions = [
    { label: '导出 Excel', value: 'Excel' },
    { label: '导出 CSV', value: 'Csv' },
    { label: '导出 JSON', value: 'Json' },
    { label: '导出 XML', value: 'Xml' },
    { label: '导出模板', value: 'ExcelTemplate' },
  ];

  private routeSub?: Subscription;

  get formFields(): DataField[] {
    return this.isEdit ? this.editFields : this.addFields;
  }

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private api: ApiService,
    private userService: UserService,
    private message: NzMessageService,
  ) {}

  ngOnInit() {
    this.routeSub = this.route.url.subscribe((segments) => {
      this.typePath = '/' + segments.map(s => s.path).join('/');
      this.pageIndex = 1;
      this.updatePermissions();
      this.loadFields().then(() => this.loadData());
      this.loadChartData();
    });
    window.addEventListener('resize', this.resizeHandler);
  }

  ngOnDestroy() {
    this.routeSub?.unsubscribe();
    window.removeEventListener('resize', this.resizeHandler);
    this.disposeCharts();
  }

  ngAfterViewChecked() {
    if (this.chartList.length && this.chartContainers?.length && !this.chartsInitialized) {
      this.initCharts();
      this.chartsInitialized = true;
    }
  }

  private updatePermissions() {
    const perms = this.userService.getMenuPermission(this.typePath);
    this.canAdd = String(Auth.ADD) in perms;
    this.canEdit = String(Auth.EDIT) in perms;
    this.canDelete = String(Auth.DELETE) in perms;
    this.canExport = String(Auth.EXPORT) in perms;
    this.canImport = String(Auth.IMPORT) in perms;
  }

  private disposeCharts() {
    for (const inst of this.chartInstances) { inst?.dispose(); }
    this.chartInstances = [];
    this.chartsInitialized = false;
  }

  private initCharts() {
    this.disposeCharts();
    this.chartContainers.forEach((ref, idx) => {
      const opt = this.chartList[idx];
      if (!opt) return;
      const instance = echarts.init(ref.nativeElement);
      instance.setOption(opt);
      this.chartInstances.push(instance);
    });
  }

  async loadChartData() {
    try {
      const res = await this.api.page.getChartData(this.typePath);
      this.chartList = Array.isArray(res.data) && res.data.length > 0 ? res.data : [];
      this.chartsInitialized = false;
    } catch {
      this.chartList = [];
    }
  }

  async loadFields() {
    const path = this.typePath;
    const [list, search, add, edit, detail] = await Promise.all([
      this.api.page.getFields(path, FieldKind.List),
      this.api.page.getFields(path, FieldKind.Search),
      this.api.page.getFields(path, FieldKind.Add),
      this.api.page.getFields(path, FieldKind.Edit),
      this.api.page.getFields(path, FieldKind.Detail),
    ]);
    this.listFields = list.data || [];
    this.searchFields = search.data || [];
    this.addFields = add.data || [];
    this.editFields = edit.data || [];
    this.detailFields = detail.data || [];
  }

  async loadData() {
    this.loading = true;
    try {
      const res = await this.api.page.getList(this.typePath, {
        pageIndex: this.pageIndex - 1,
        pageSize: this.pageSize,
        ...this.searchForm,
      });
      this.tableData = res.data || [];
      this.statData = (res as any).stat ?? null;
      if (res.page) this.total = res.page.totalCount || 0;
    } finally {
      this.loading = false;
    }
  }

  onPageChange(page: number) {
    this.pageIndex = page;
    this.loadData();
  }

  onPageSizeChange(size: number) {
    this.pageSize = size;
    this.pageIndex = 1;
    this.loadData();
  }

  onAllChecked(checked: boolean) {
    if (checked) {
      this.tableData.forEach(r => this.checkedIds.add(r['id']));
    } else {
      this.checkedIds.clear();
    }
  }

  onItemChecked(id: number, checked: boolean) {
    if (checked) this.checkedIds.add(id);
    else this.checkedIds.delete(id);
    this.allChecked = this.tableData.length > 0 && this.tableData.every(r => this.checkedIds.has(r['id']));
  }

  handleSearch() {
    this.pageIndex = 1;
    this.loadData();
  }

  handleReset() {
    this.searchForm = {};
    this.pageIndex = 1;
    this.loadData();
  }

  handleAdd() {
    this.isEdit = false;
    this.formData = {};
    this.formVisible = true;
  }

  handleEdit(row: Record<string, any>) {
    this.isEdit = true;
    this.formData = { ...row };
    this.formVisible = true;
  }

  async handleFormSubmit() {
    this.submitLoading = true;
    try {
      if (this.isEdit) {
        await this.api.page.update(this.typePath, this.formData);
      } else {
        await this.api.page.add(this.typePath, this.formData);
      }
      this.message.success(this.isEdit ? '编辑成功' : '新增成功');
      this.formVisible = false;
      this.loadData();
    } catch {
      this.message.error('操作失败');
    } finally {
      this.submitLoading = false;
    }
  }

  handleDetail(row: Record<string, any>) {
    this.detailData = { ...row };
    this.detailVisible = true;
  }

  async handleDelete(row: Record<string, any>) {
    await this.api.page.remove(this.typePath, row['id']);
    this.message.success('删除成功');
    this.loadData();
  }

  async handleBatchDelete() {
    if (!this.checkedIds.size) return;
    await this.api.page.deleteSelect(this.typePath, Array.from(this.checkedIds));
    this.message.success('批量删除成功');
    this.checkedIds.clear();
    this.allChecked = false;
    this.loadData();
  }

  handleExport(fmt: string) {
    window.open(this.api.page.getExportUrl(this.typePath, fmt), '_blank');
  }

  onImportChange(event: any) {
    if (event.type === 'success') {
      this.message.success('导入成功');
      this.loadData();
    }
  }
}
